# Category-reranked object RAG: design and plan

Question + category → mapped active documents across categories → eligible table/outer-row vectors → cosine candidate pool → category score reranking → exact cited evidence → Ollama code answer.

Retrieve up to four times `top_k` cosine matches, then rank by `score = (1 - cosine_distance) + CATEGORY_SCORE_BOOST * category_match`. The default bonus is `0.15`; configure `OBJECT_RAG_CATEGORY_BOOST` or `CATEGORY_SCORE_BOOST` below. Matching manual categories receive the bonus; other mapped categories remain eligible. Keep the raw distance alongside the similarity, applied bonus and final score for inspection. The constructor callback applies this ranking to direct `app.retrieve` and `app.answer` calls as well as the coverage suites. Saved outputs reflect earlier executions; restart the kernel, then rerun the configuration, service and selected retrieval/answer cells to refresh them.

Reuse the existing index without ingestion or checkpoint changes. Match the combined and V4.0/V5.0 workbook mappings through explicit corpus-root aliases, retain corpus and revision labels, and report missing coverage. Traverse row-group wrappers for outer rows; exclude cells and deeper rows from vector candidates. Validate identity, embedding configuration and dimensions; query eligible IDs before ranking.

Implementation: configure paths and services; load categories/mappings; open the catalog read-only and existing collection; inspect coverage; retrieve and inspect exact evidence; generate version-specific fenced snippets with citations; close resources. Defaults: supplied index, top-k 8, 24,000 context characters, Ollama RAG model falling back to the summary model. Complete blocks exceeding the budget are reported as omitted. Unsupported coding requests must receive an insufficient-evidence answer.

Validation: offline fake-provider and ephemeral-index tests, notebook validation and cell compilation, and read-only real catalog coverage inspection. No corpus rebuilds, summary requests or checkpoint resets.


Every answer includes a separate source-attributed summary of the retrieved objects, regardless of whether the coding request is supported.

## Application configuration

Reusable retrieval logic lives in [01.rag.object.ipynb](01.rag.object.ipynb), exported as `ribosome.rag.object`. Configuration and client lifecycle stay here.

In [1]:
# | notest
import math
import os
from pathlib import Path
import pandas as pd
from dotenv import load_dotenv
from IPython.display import Markdown, display
from ribosome.rag.object import ObjectRAG

PROJ_ROOT = Path(os.getenv("PROJ_ROOT", Path.cwd())).resolve()
while not (PROJ_ROOT / "pyproject.toml").exists() and PROJ_ROOT != PROJ_ROOT.parent:
    PROJ_ROOT = PROJ_ROOT.parent
load_dotenv(PROJ_ROOT / ".env", override=False)
# INDEX_DIR = Path(os.getenv("OBJECT_RAG_INDEX", "db/object_embeddings/qwen3-embedding-8b-20261022-152558-151254"))
INDEX_DIR = Path(os.getenv("OBJECT_RAG_INDEX", "db/object_embeddings/qwen3-embedding-8b-20261026-090625-217683"))
if not INDEX_DIR.is_absolute(): INDEX_DIR = PROJ_ROOT / INDEX_DIR
EMBED_MODEL = os.getenv("OLLAMA_EMBED_MODEL", "qwen3-embedding:8b")
HOSTS = sorted(set(x.strip().rstrip("/") for x in os.getenv("OLLAMA_EMBED_HOSTS", "http://localhost:11434,http://172.27.74.16:11434").split(",") if x.strip()))
RAG_MODEL = os.getenv("OLLAMA_RAG_MODEL") or os.getenv("OLLAMA_SUMMARY_MODEL", "")
RAG_HOST = os.getenv("OLLAMA_RAG_HOST") or os.getenv("OLLAMA_HOST", "http://localhost:11434")
MAX_CONTEXT_CHARS = 24000
REQUEST_TIMEOUT = 300
MAX_OUTPUT_TOKENS = 2048
CATEGORY_SCORE_BOOST = float(os.getenv("OBJECT_RAG_CATEGORY_BOOST", "0.15"))
if not math.isfinite(CATEGORY_SCORE_BOOST) or CATEGORY_SCORE_BOOST < 0:
    raise ValueError("OBJECT_RAG_CATEGORY_BOOST must be finite and nonnegative")

def rerank_by_category(hits, category):
    """Boost matching manual labels while retaining semantic similarity."""
    scored = []
    for hit in hits:
        similarity = 1.0 - hit["distance"]
        category_match = hit["manual"]["category"] == category
        boost = CATEGORY_SCORE_BOOST if category_match else 0.0
        scored.append(dict(hit, similarity=similarity, category_match=category_match,
                           category_boost=boost, score=similarity + boost))
    return sorted(scored, key=lambda hit: (-hit["score"], hit["distance"], hit["record"]["id"]))

## Open existing index and services
Run explicitly; no embedding or generation occurs in this cell.

In [2]:
# | notest
import chromadb
from ollama import AsyncClient
if not (INDEX_DIR / 'catalog.sqlite3').is_file() or not (INDEX_DIR / 'chroma').is_dir():
    raise FileNotFoundError(INDEX_DIR)
headers = {'Authorization': 'Bearer '+os.environ['OLLAMA_API_KEY']} if os.getenv('OLLAMA_API_KEY') else {}
embedding_client = AsyncClient(host=HOSTS[0], headers=headers, timeout=REQUEST_TIMEOUT)
generation_client = AsyncClient(host=RAG_HOST, headers=headers, timeout=REQUEST_TIMEOUT)
collection = chromadb.PersistentClient(path=str(INDEX_DIR/'chroma')).get_collection('object_summaries', embedding_function=None)
app = ObjectRAG(
    INDEX_DIR, collection, embedding_client, generation_client,
    mapping_dir=PROJ_ROOT / 'assets/coding_categories',
    embed_model=EMBED_MODEL,
    embedding_config=dict(provider='ollama-pool', hosts=HOSTS),
    rag_model=RAG_MODEL, max_context_chars=MAX_CONTEXT_CHARS,
    max_output_tokens=MAX_OUTPUT_TOKENS, rerank=rerank_by_category,
)
async def retrieve(question, category, *, top_k=8):
    return await app.retrieve(question, category, top_k=top_k)
async def answer(question, category, *, top_k=8):
    return await app.answer(question, category, top_k=top_k)

## Category coverage

This suite has one prompt for each of the **17 application categories other than
`general_operation`**. Questions may use either mapped manual revision, with the
answer identifying its source. The dedicated manual-version suites and expanded CSV evaluation now live in
[06.test.rag.object.ipynb](06.test.rag.object.ipynb).

Set `COVERAGE_CASE_IDS` to selected category case IDs, or leave it `None` for all
17 prompts. The following two sections retrieve evidence and generate answers for
this suite only. Defining or displaying prompts makes no model requests. Shared
helpers also serve the separate manual suite, which has its own selection and
result dictionaries.

In [3]:
# | notest
COVERAGE_CASES = [{'id': 'category_adhesive_dispensing',
  'category': 'adhesive_dispensing',
  'kind': 'category',
  'profile': '',
  'revision': '',
  'section': '',
  'section_title': '',
  'anchors': [],
  'question': '如何按涂胶手册配置胶机并编写一次涂胶流程，包含开始出胶、沿轨迹涂胶和停止出胶？请说明工艺文件和IO的准备条件。',
  'references': []},
 {'id': 'category_arc_welding',
  'category': 'arc_welding',
  'kind': 'category',
  'profile': '',
  'revision': '',
  'section': '',
  'section_title': '',
  'anchors': [],
  'question': '如何使用ARCON开始弧焊、沿焊缝运动并用ARCOFF结束焊接？请说明起弧文件与焊接文件的区别。',
  'references': []},
 {'id': 'category_fds',
  'category': 'fds',
  'kind': 'category',
  'profile': '',
  'revision': '',
  'section': '',
  'section_title': '',
  'anchors': [],
  'question': '如何按FDS手册配置主机工作参数和IO，并组织一次FDS作业的启动、完成状态确认及后续动作？',
  'references': []},
 {'id': 'category_grinding',
  'category': 'grinding',
  'kind': 'category',
  'profile': '',
  'revision': '',
  'section': '',
  'section_title': '',
  'anchors': [],
  'question': '如何首次配置打磨力控制器并完成标定，再设置打磨力、位移及出入刀监控，组织一次打磨作业？',
  'references': []},
 {'id': 'category_laser_welding',
  'category': 'laser_welding',
  'kind': 'category',
  'profile': '',
  'revision': '',
  'section': '',
  'section_title': '',
  'anchors': [],
  'question': '激光焊作业需要哪些激光器、通讯和IO配置？如何按手册组织激光开启、焊接运动和激光关闭的程序？',
  'references': []},
 {'id': 'category_load_analysis',
  'category': 'load_analysis',
  'kind': 'category',
  'profile': '',
  'revision': '',
  'section': '',
  'section_title': '',
  'anchors': [],
  'question': '使用负载分析软件时，如何确认工具数模坐标系与机器人法兰坐标系一致，并查看和解释负载分析结果？只需说明操作流程，不要虚构控制指令。',
  'references': []},
 {'id': 'category_material_handling',
  'category': 'material_handling',
  'kind': 'category',
  'profile': '',
  'revision': '',
  'section': '',
  'section_title': '',
  'anchors': [],
  'question': '如何配置搬运应用的抓手、工件传感器和电磁阀，并组织抓取工件、确认抓取状态、搬运后释放的作业？',
  'references': []},
 {'id': 'category_offline_interface',
  'category': 'offline_interface',
  'kind': 'category',
  'profile': '',
  'revision': '',
  'section': '',
  'section_title': '',
  'anchors': [],
  'question': '使用新松机器人离线接口库时，上位机初始化、建立网络连接、发送运动或下载作业、断开并释放资源的正确调用顺序是什么？请选择一种手册支持的语言举例。',
  'references': []},
 {'id': 'category_palletizing',
  'category': 'palletizing',
  'kind': 'category',
  'profile': '',
  'revision': '',
  'section': '',
  'section_title': '',
  'anchors': [],
  'question': '如何从开启码垛应用、PLC通讯准备、工具与用户坐标系设置开始，配置产品和码垛工艺，再组织一次码垛作业？',
  'references': []},
 {'id': 'category_pneumatic_spot_welding',
  'category': 'pneumatic_spot_welding',
  'kind': 'category',
  'profile': '',
  'revision': '',
  'section': '',
  'section_title': '',
  'anchors': [],
  'question': '如何配置气动点焊的设备交互IO、焊接压力和焊点参数，并组织加压、焊接、完成确认及松开焊钳的流程？',
  'references': []},
 {'id': 'category_spot_welding',
  'category': 'spot_welding',
  'kind': 'category',
  'profile': '',
  'revision': '',
  'section': '',
  'section_title': '',
  'anchors': [],
  'question': '伺服点焊作业前如何完成焊钳轴校零、压力标定和焊点参数配置，并组织一次加压、焊接及打开焊钳的流程？',
  'references': []},
 {'id': 'category_spr_riveting',
  'category': 'spr_riveting',
  'kind': 'category',
  'profile': '',
  'revision': '',
  'section': '',
  'section_title': '',
  'anchors': [],
  'question': '如何配置SPR铆机的工作模式、IO及通讯，并按基本作业流程完成一次铆接和防漏铆确认？',
  'references': []},
 {'id': 'category_stud_welding',
  'category': 'stud_welding',
  'kind': 'category',
  'profile': '',
  'revision': '',
  'section': '',
  'section_title': '',
  'anchors': [],
  'question': '如何配置螺柱焊焊机的工作参数、IO及通讯，并按基本作业流程完成一次焊接及防漏焊确认？',
  'references': []},
 {'id': 'category_teaching_free_welding',
  'category': 'teaching_free_welding',
  'kind': 'category',
  'profile': '',
  'revision': '',
  'section': '',
  'section_title': '',
  'anchors': [],
  'question': '免示教焊接软件如何配置机器人与视觉设备、创建工件、设置扫描区域和焊缝规则，再规划并执行焊接任务？请区分服务端配置和客户端操作。',
  'references': []},
 {'id': 'category_tool_quick_change',
  'category': 'tool_quick_change',
  'kind': 'category',
  'profile': '',
  'revision': '',
  'section': '',
  'section_title': '',
  'anchors': [],
  'question': '如何配置快换停靠站、快换盘和IO，并组织放下当前工具、确认解锁、拾取目标工具和确认锁紧的基本作业流程？',
  'references': []},
 {'id': 'category_tracking',
  'category': 'tracking',
  'kind': 'category',
  'profile': '',
  'revision': '',
  'section': '',
  'section_title': '',
  'anchors': [],
  'question': '如何使用FL_GETV读取第一路传送带的实时速度，并在跟随作业中使用该速度？请说明R变量、通路参数及单位。',
  'references': []},
 {'id': 'category_vision',
  'category': 'vision',
  'kind': 'category',
  'profile': '',
  'revision': '',
  'section': '',
  'section_title': '',
  'anchors': [],
  'question': '如何给相机发送拍照指令、获取测量结果并计算位姿偏移？请按同一手册版本说明视觉作业参数及指令调用顺序。',
  'references': []}]

In [4]:
# | notest
import html
import re
from copy import deepcopy

def coverage_plain(text):
    return ' '.join(html.unescape(re.sub(r'<[^>]*>', ' ', text)).split())

def coverage_heading_title(heading):
    title = re.sub(r'^\s*\d+(?:\.\d+)*\s+', '', heading.strip('* '))
    return re.sub(r'\s+', '', title).translate(str.maketrans({'—': '-', '–': '-', '－': '-'}))

def coverage_heading_path_matches(expected_path, headings):
    remaining = iter(coverage_heading_title(heading) for heading in headings)
    return all(any(title == coverage_heading_title(expected) for title in remaining)
               for expected in expected_path)

def coverage_case_metrics(case, result, error=''):
    hits = result.get('hits', [])
    # Version-specific cases must find their own corpus and manual, even though
    # production retrieval is category-reranked and may return both revisions.
    matching = [hit for hit in hits if not case['profile'] or (
        hit['manual']['profile'] == case['profile'] and
        Path(hit['record']['source_file']).stem == Path(case['references'][0]['docx']).stem)]
    headings = [heading.split(maxsplit=1)[0] for hit in matching
                for heading in hit['record'].get('section_headings', []) if heading.strip()]
    if case.get('heading_path'):
        section_hit = any(coverage_heading_path_matches(
            case['heading_path'], hit['record'].get('section_headings', [])) for hit in matching)
    else:
        section_hit = case['section'] in headings if case['section'] else None
    source_text = '\n'.join(coverage_plain(hit['record']['content']) for hit in matching)
    anchors_found = all(re.search(r'(?<![A-Za-z0-9_])'+re.escape(term)+r'(?![A-Za-z0-9_])',
                                 source_text, flags=re.IGNORECASE) for term in case['anchors'])
    return dict(case_id=case['id'], category=case['category'], kind=case['kind'],
                expected_revision=case['revision'], expected_section=case['section'],
                hits=len(hits), expected_manual_hit=bool(matching) if case['profile'] else None,
                expected_section_hit=section_hit,
                anchors_in_matching_hits=anchors_found if case['anchors'] else None,
                context_chars=len(result.get('context', '')), omissions=len(result.get('omissions', [])),
                missing_manuals=len(result.get('coverage', {}).get('missing', [])), error=error)

def show_coverage_retrieval(case_id, *, cases=None, results=None, errors=None):
    cases = coverage_cases if cases is None else cases
    results = coverage_retrieval_results if results is None else results
    errors = coverage_retrieval_errors if errors is None else errors
    case = next(case for case in cases if case['id'] == case_id)
    display(Markdown(f"### {case_id}\n\n{case['question']}"))
    if case_id in errors:
        print(errors[case_id])
        return
    result = results[case_id]
    display(pd.DataFrame([dict(score=hit.get('score'), similarity=hit.get('similarity'),
                               category_match=hit.get('category_match'),
                               category_boost=hit.get('category_boost'),
                               distance=hit['distance'], manual=hit['manual'],
                               lines=(hit['record']['attributes'].get('line_start'),
                                      hit['record']['attributes'].get('line_end')),
                               summary=hit['record'].get('summary', ''),
                               source=hit['record']['source_file']) for hit in result['hits']]))
    print(result['context'])
    print('Omitted:', result['omissions'])
    # Reference excerpts remain reviewer data and are never added to the prompt.
    if case['references']:
        display(pd.DataFrame(case['references']))

class CoverageAnswerReplay(ObjectRAG):
    """Run the production answer method on the exact retrieved test evidence."""
    def __init__(self, application, evidence, *, top_k=8):
        self.generator = application.generator
        self.rag_model = application.rag_model
        self.max_output_tokens = application.max_output_tokens
        self.evidence = evidence
        self.top_k = top_k
        self.last_result = None

    async def retrieve(self, question, category, *, top_k=8):
        if (question, category, top_k) != (
            self.evidence['question'], self.evidence['category'], self.top_k
        ):
            raise ValueError('Coverage replay requires the same question, category and top-k')
        self.last_result = deepcopy(self.evidence)
        return self.last_result

async def run_coverage_retrievals(application, cases, *, top_k, results, errors):
    """Retrieve into this suite's dictionaries; retain completed cases on interruption."""
    for number, case in enumerate(cases, 1):
        print(f"[{number}/{len(cases)}] Retrieve {case['id']}", flush=True)
        try:
            results[case['id']] = await application.retrieve(
                case['question'], case['category'], top_k=top_k)
        except Exception as error:
            errors[case['id']] = f'{type(error).__name__}: {error}'
    return pd.DataFrame([
        coverage_case_metrics(case, results.get(case['id'], {}),
                              errors.get(case['id'], ''))
        for case in cases])

async def run_coverage_answers(application, cases, *, top_k, retrieval_results,
                               retrieval_errors, results, errors):
    """Answer from this suite's frozen evidence; never make another retrieval request."""
    for number, case in enumerate(cases, 1):
        case_id = case['id']
        display(Markdown(f"## [{number}/{len(cases)}] {case_id}\n\n{case['question']}"))
        if case_id not in retrieval_results:
            errors[case_id] = retrieval_errors.get(case_id, 'Retrieve this case first')
            display(Markdown('Retrieval failed: ' + errors[case_id]))
            continue
        replay = CoverageAnswerReplay(application, retrieval_results[case_id], top_k=top_k)
        try:
            results[case_id] = await replay.answer(
                case['question'], case['category'], top_k=top_k)
        except Exception as error:
            errors[case_id] = f'{type(error).__name__}: {error}'
            results[case_id] = replay.last_result or {}
        finally:
            if case_id not in results and replay.last_result is not None:
                results[case_id] = replay.last_result
                errors[case_id] = 'Generation interrupted before completion'
            case_result = results.get(case_id, {})
            if 'retrieved_summary' in case_result:
                display(Markdown('### Retrieved content summary\n\n' + case_result['retrieved_summary']))
        if case_id in errors:
            display(Markdown('Generation failed: ' + errors[case_id]))
        else:
            display(Markdown('### Coding or diagnostic answer\n\n' + case_result['answer']))
    return pd.DataFrame([
        dict(**coverage_case_metrics(case, results.get(case['id'], {}),
                                     errors.get(case['id'], '')),
             example_status=results.get(case['id'], {}).get('example_status', 'not generated'))
        for case in cases])

In [5]:
# | notest
display(pd.DataFrame([(category, name) for category, name in app.categories.items()
                      if category != 'general_operation'], columns=['category', 'chinese_name']))
assert {case['category'] for case in COVERAGE_CASES} == set(app.categories) - {'general_operation'}
COVERAGE_TOP_K = 8
COVERAGE_CASE_IDS = None  # Example: ['category_arc_welding', 'category_vision']
known_case_ids = {case['id'] for case in COVERAGE_CASES}
if COVERAGE_CASE_IDS is not None:
    if not COVERAGE_CASE_IDS or set(COVERAGE_CASE_IDS) - known_case_ids:
        raise ValueError('Select at least one known coverage case ID')
coverage_cases = [case for case in COVERAGE_CASES
                  if COVERAGE_CASE_IDS is None or case['id'] in COVERAGE_CASE_IDS]
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    display(pd.DataFrame(coverage_cases)[
        ['id', 'category', 'question']])
category_coverage_rows = []
for category in dict.fromkeys(case['category'] for case in coverage_cases):
    mapped_coverage = app.snapshot(category)[2]
    category_coverage_rows.append(dict(category=category, indexed=mapped_coverage['indexed'],
                                       missing=mapped_coverage['missing']))
display(pd.DataFrame(category_coverage_rows))

                  category chinese_name
0      adhesive_dispensing           涂胶
1              arc_welding           弧焊
2                      fds          FDS
3                 grinding           打磨
4            laser_welding          激光焊
5            load_analysis         负载分析
6        material_handling           搬运
7        offline_interface         离线接口
8              palletizing           码垛
9   pneumatic_spot_welding         气动点焊
10            spot_welding           点焊
11            spr_riveting        SPR铆接
12            stud_welding          螺柱焊
13   teaching_free_welding        免示教焊接
14       tool_quick_change           快换
15                tracking           跟随
16                  vision           视觉

,id,category,question
0,category_adhesive_dispensing,adhesive_dispensing,如何按涂胶手册配置胶机并编写一次涂胶流程，包含开始出胶、沿轨迹涂胶和停止出胶？请说明工艺文件和IO的准备条件。
1,category_arc_welding,arc_welding,如何使用ARCON开始弧焊、沿焊缝运动并用ARCOFF结束焊接？请说明起弧文件与焊接文件的区别。
2,category_fds,fds,如何按FDS手册配置主机工作参数和IO，并组织一次FDS作业的启动、完成状态确认及后续动作？
3,category_grinding,grinding,如何首次配置打磨力控制器并完成标定，再设置打磨力、位移及出入刀监控，组织一次打磨作业？
4,category_laser_welding,laser_welding,激光焊作业需要哪些激光器、通讯和IO配置？如何按手册组织激光开启、焊接运动和激光关闭的程序？
5,category_load_analysis,load_analysis,使用负载分析软件时，如何确认工具数模坐标系与机器人法兰坐标系一致，并查看和解释负载分析结果？只需说明操作流程，不要虚构控制指令。
6,category_material_handling,material_handling,如何配置搬运应用的抓手、工件传感器和电磁阀，并组织抓取工件、确认抓取状态、搬运后释放的作业？
7,category_offline_interface,offline_interface,使用新松机器人离线接口库时，上位机初始化、建立网络连接、发送运动或下载作业、断开并释放资源的正确调用顺序是什么？请选择一种手册支持的语言举例。
8,category_palletizing,palletizing,如何从开启码垛应用、PLC通讯准备、工具与用户坐标系设置开始，配置产品和码垛工艺，再组织一次码垛作业？
9,category_pneumatic_spot_welding,pneumatic_spot_welding,如何配置气动点焊的设备交互IO、焊接压力和焊点参数，并组织加压、焊接、完成确认及松开焊钳的流程？
10,category_spot_welding,spot_welding,伺服点焊作业前如何完成焊钳轴校零、压力标定和焊点参数配置，并组织一次加压、焊接及打开焊钳的流程？
11,category_spr_riveting,spr_riveting,如何配置SPR铆机的工作模式、IO及通讯，并按基本作业流程完成一次铆接和防漏铆确认？
12,category_stud_welding,stud_welding,如何配置螺柱焊焊机的工作参数、IO及通讯，并按基本作业流程完成一次焊接及防漏焊确认？
13,category_teaching_free_welding,teaching_free_welding,免示教焊接软件如何配置机器人与视觉设备、创建工件、设置扫描区域和焊缝规则，再规划并执行焊接任务？请区分服务端配置和客户端操作。
14,category_tool_quick_change,tool_quick_change,如何配置快换停靠站、快换盘和IO，并组织放下当前工具、确认解锁、拾取目标工具和确认锁紧的基本作业流程？
15,category_tracking,tracking,如何使用FL_GETV读取第一路传送带的实时速度，并在跟随作业中使用该速度？请说明R变量、通路参数及单位。
16,category_vision,vision,如何给相机发送拍照指令、获取测量结果并计算位姿偏移？请按同一手册版本说明视觉作业参数及指令调用顺序。

,category,indexed,missing
0,adhesive_dispensing,[{'key': '06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人...,[]
1,arc_welding,[{'key': '06 产品手册/软件类/手册/V5.0版本/SX322003《新松机器人...,[]
2,fds,[{'key': '06 产品手册/软件类/手册/V5.0版本/SX322016《新松机器人...,[]
3,grinding,[{'key': '06 产品手册/软件类/手册/V5.0版本/SX322006《新松机器人...,[]
4,laser_welding,[{'key': '06 产品手册/软件类/手册/V5.0版本/SX322004《新松机器人...,[]
5,load_analysis,[{'key': '06 产品手册/软件类/手册/V3.0版本/SX322010《新松机器人...,[]
6,material_handling,[{'key': '06 产品手册/软件类/手册/V5.0版本/SX322011《新松机器人...,[]
7,offline_interface,[{'key': '06 产品手册/软件类/手册/V5.0版本/SX322009《新松机器人...,[]
8,palletizing,[{'key': '06 产品手册/软件类/手册/V5.0版本/SX322002《新松机器人...,[]
9,pneumatic_spot_welding,[{'key': '06 产品手册/软件类/手册/V5.0版本/SX322018《新松机器人...,[]
10,spot_welding,[{'key': '06 产品手册/软件类/手册/V5.0版本/SX322007《新松机器人...,[]
11,spr_riveting,[{'key': '06 产品手册/软件类/手册/V5.0版本/SX322014《新松机器人...,[]
12,stud_welding,[{'key': '06 产品手册/软件类/手册/V5.0版本/SX322013《新松机器人...,[]
13,teaching_free_welding,[{'key': '06 产品手册/软件类/手册/V3.0版本/SX322008《新松机器人...,[]
14,tool_quick_change,[{'key': '06 产品手册/软件类/手册/V5.0版本/SX322015《新松机器人...,[]
15,tracking,[{'key': '06 产品手册/软件类/手册/V5.0版本/SX322017《新松机器人...,[]
16,vision,[{'key': '06 产品手册/软件类/手册/V5.0版本/SX322005《新松机器人...,[]

In [6]:
# | notest
INSPECT_CASE_ID = coverage_cases[0]['id']  # Change to any selected ID to inspect its exact evidence.

## Retrieve and inspect exact evidence

Run the selected category prompts through the existing category-reranked retriever.
Results are retained by case ID in `coverage_retrieval_results`, with per-case
failures in `coverage_retrieval_errors`; completed results remain inspectable after
interruption. Use `show_coverage_retrieval(case_id)` for any selected category case
to inspect the matched objects, raw context and omissions.

The category table reports hit count, context size, omitted objects, missing mapped
manuals and errors. These are retrieval diagnostics, not answer-correctness scores.
Version, subsection and alarm-code checks belong to the dedicated manual suite
below. The original production candidate restrictions still apply.

In [7]:
# | notest
coverage_retrieval_results, coverage_retrieval_errors = {}, {}
coverage_retrieval_metrics = await run_coverage_retrievals(
    app, coverage_cases, top_k=COVERAGE_TOP_K,
    results=coverage_retrieval_results, errors=coverage_retrieval_errors)
display(coverage_retrieval_metrics[
    ['case_id', 'category', 'hits', 'context_chars', 'omissions', 'missing_manuals', 'error']])
show_coverage_retrieval(INSPECT_CASE_ID)

[1/17] Retrieve category_adhesive_dispensing
[2/17] Retrieve category_arc_welding
[3/17] Retrieve category_fds
[4/17] Retrieve category_grinding
[5/17] Retrieve category_laser_welding
[6/17] Retrieve category_load_analysis
[7/17] Retrieve category_material_handling
[8/17] Retrieve category_offline_interface
[9/17] Retrieve category_palletizing
[10/17] Retrieve category_pneumatic_spot_welding
[11/17] Retrieve category_spot_welding
[12/17] Retrieve category_spr_riveting
[13/17] Retrieve category_stud_welding
[14/17] Retrieve category_teaching_free_welding
[15/17] Retrieve category_tool_quick_change
[16/17] Retrieve category_tracking
[17/17] Retrieve category_vision

,case_id,category,hits,context_chars,omissions,missing_manuals,error
0,category_adhesive_dispensing,adhesive_dispensing,8,12971,0,0,
1,category_arc_welding,arc_welding,8,17215,0,0,
2,category_fds,fds,8,6403,0,0,
3,category_grinding,grinding,8,10491,0,0,
4,category_laser_welding,laser_welding,8,11921,0,0,
5,category_load_analysis,load_analysis,8,4460,0,0,
6,category_material_handling,material_handling,8,9870,0,0,
7,category_offline_interface,offline_interface,8,18685,0,0,
8,category_palletizing,palletizing,8,8970,0,0,
9,category_pneumatic_spot_welding,pneumatic_spot_welding,8,9161,0,0,
10,category_spot_welding,spot_welding,8,7826,0,0,
11,category_spr_riveting,spr_riveting,8,10825,0,0,
12,category_stud_welding,stud_welding,8,10354,0,0,
13,category_teaching_free_welding,teaching_free_welding,8,10372,0,0,
14,category_tool_quick_change,tool_quick_change,8,8147,0,0,
15,category_tracking,tracking,8,7859,0,0,
16,category_vision,vision,8,6530,0,0,

### category_adhesive_dispensing

如何按涂胶手册配置胶机并编写一次涂胶流程，包含开始出胶、沿轨迹涂胶和停止出胶？请说明工艺文件和IO的准备条件。

,score,similarity,category_match,category_boost,distance,manual,lines,summary,source
0,0.859229,0.709229,True,0.15,0.290771,{'key': '06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂...,"(701, 778)",该表展示了一段机器人涂胶程序的完整流程，按行顺序定义了**坐标系/负载配置**、**运动路径...,/d/devel/rag/ribosome/assets/code-docs.5.0/.md...
1,0.837284,0.687284,True,0.15,0.312716,{'key': '06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂...,"(388, 392)",涂胶结束指令集功能：涂胶结束，进行测量并根据参数是否进行填充,/d/devel/rag/ribosome/assets/code-docs.4.0/.md...
2,0.815880,0.665880,True,0.15,0.334120,{'key': '06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂...,"(784, 877)",该表格展示了一段机器人涂胶应用的 PLC 控制逻辑，主要流程为：**前置条件校验 -> 系统...,/d/devel/rag/ribosome/assets/code-docs.4.0/.md...
3,0.807394,0.657394,True,0.15,0.342606,{'key': '06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂...,"(384, 387)",涂胶初始化指令集举例：A08_GLUE GlueInit Gun=1 ProgNo=1 Pa...,/d/devel/rag/ribosome/assets/code-docs.4.0/.md...
4,0.803008,0.653008,True,0.15,0.346992,{'key': '06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂...,"(469, 472)",在“设置涂胶系统指令集”模块下，该行为示例条目，展示了设置涂胶系统的指令格式：`A08_GL...,/d/devel/rag/ribosome/assets/code-docs.4.0/.md...
5,0.802646,0.652646,True,0.15,0.347354,{'key': '06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂...,"(784, 877)",该表格展示了一段用于控制胶涂覆系统的梯形图或逻辑指令序列，主要执行流程包括：\n\n1. ...,/d/devel/rag/ribosome/assets/code-docs.5.0/.md...
6,0.783083,0.633083,True,0.15,0.366917,{'key': '06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂...,"(298, 350)",该表格定义了三种**GLUEL** 涂胶控制指令，分别对应不同的胶枪状态操作。各指令结构相似...,/d/devel/rag/ribosome/assets/code-docs.5.0/.md...
7,0.782231,0.632231,True,0.15,0.367769,{'key': '06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂...,"(376, 379)",涂胶初始化指令集：格式为 `A08_GLUE GlueInit Gun= ProgNo= P...,/d/devel/rag/ribosome/assets/code-docs.4.0/.md...

[E1] {'key': '06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂胶应用操作手册》(A-1)/SX322012《新松机器人涂胶应用操作手册》(A-1)', 'profile': '5.0', 'revision': 'V5.0 / A-1', 'category': 'adhesive_dispensing'} | /d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂胶应用操作手册》(A-1)/SX322012《新松机器人涂胶应用操作手册》(A-1).md | lines 701-778 | 37c4f5108de3bb61e98ae85067745cd52c511dea5e3d0119a6a9619c1525326f
<table>
<tr>
<td><p>NOP   </p></td>
<td></td>
</tr>
<tr>
<td><p>SET UF   &#35;0</p></td>
<td><p>用户坐标系选择</p></td>
</tr>
<tr>
<td><p>SET TF   &#35;1</p></td>
<td><p>工具坐标系选择</p></td>
</tr>
<tr>
<td><p>PAYLOAD   &#35;1</p></td>
<td><p>负载&#45;抓手加车架</p></td>
</tr>
<tr>
<td><p>MOVJ	PR102 VJ=30&#46;0 ACC=30 CNT=0</p></td>
<td><p>冲锋位</p></td>
</tr>
<tr>
<td><p>MOVJ	P1 VJ=30&#46;0 ACC=100 CNT=1</p></td>
<td></td>
</tr>
<tr>
<td><p>;</p></td>
<td></td>
</tr>
<tr>
<td><p>A08&#95;GLUE GlueSetSysNum SysNum=1</p></td>
<td><p>设置涂胶系统</p></td>
</tr>
<tr>
<td><p>A08&#95;GLUE GlueInit Gun=1 ProgNo=1 ParaNo=1 Purge=Yes Fill=Yes</p></td>
<td><p>涂胶初始化</p></td>
</tr>
<tr>
<td><p>MOVL	P4 VL=1000&#46;0 ACC=100 CNT=30 ET=1</p></td>
<td></td>
</tr>
<tr>
<td><p>GLUEL  P1 VL=300 ACC=100 CNT=10 ET=1 GLUEON GUN=1 CALIB=1 PARANo =1 TIME =20 </p></td>
<td><p>开胶</p></td>
</tr>
<tr>
<td><p>GLUEL  P1 VL=300 ACC=100 CNT=10 ET=1 GLUEOFF TIME=20</p></td>
<td><p>关胶</p></td>
</tr>
<tr>
<td><p>MOVL	P4 VL=1000&#46;0 ACC=100 CNT=30 ET=1</p></td>
<td></td>
</tr>
<tr>
<td><p>A08&#95;GLUE GlueEnd Gun=1 Fill=No</p></td>
<td><p>循环结束</p></td>
</tr>
<tr>
<td><p>A08&#95;GLUE GlueFillCheck Gun=1 Check</p></td>
<td><p>填充检查（SCA胶机循环结束后回自动填充）</p></td>
</tr>
<tr>
<td><p>MOVJ	P2 VJ=30&#46;0 ACC=100 CNT=1</p></td>
<td></td>
</tr>
<tr>
<td><p>MOVJ	PR102 VJ=30&#46;0 ACC=30 CNT=0</p></td>
<td><p>回冲锋位</p></td>
</tr>
<tr>
<td><p>RET</p></td>
<td></td>
</tr>
<tr>
<td><p>END</p></td>
<td></td>
</tr>
</table>
[]

[E2] {'key': '06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂胶应用操作手册》(A-1)/SX322012《新松机器人涂胶应用操作手册》(A-1)', 'profile': '4.0', 'revision': 'V5.0 / A-1', 'category': 'adhesive_dispensing'} | /d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂胶应用操作手册》(A-1)/SX322012《新松机器人涂胶应用操作手册》(A-1).md | lines 388-392 | ad90fdf2195c5a0665d2ed14a835fb0bc4d3e070ab3f50b3d900862f07b0f2ce
Parent table context, source lines 370-473:
<table>
<tr>
<td rowspan="4"><p>涂胶初始化指令集</p></td>
<td><p>功能</p></td>
<td><p>涂胶初始化</p></td>
</tr>
<tr>
<td><p>格式</p></td>
<td><p>A08&#95;GLUE GlueInit Gun= ProgNo= ParaNo= Purge=No/Yes/Auto  Fill=No/Yes/ Auto注释</p></td>
</tr>
<tr>
<td><p>说明</p></td>
<td><p>&lt;参数1&gt;：功能定义；</p><p>&lt;参数2&gt;：定量机号；<strong>存外部实型变量491</strong>；</p><p>&lt;参数3&gt;：程序号；<strong>存外部实型变量492</strong>；</p><p>&lt;参数4&gt;：参数号；<strong>存外部实型变量493</strong>；</p><p>&lt;参数5&gt;：冲洗（1不冲洗/2强制冲洗/3根据是否有请求冲洗）；<strong>存外部实型变量494；</strong></p><p>&lt;参数6&gt;：填充（1不填充/2强制填充/3根据是否有请求填充）；<strong>存外部实型变量495；</strong></p><p>&lt;参数7&gt;：注释；</p></td>
</tr>
<tr>
<td><p>举例</p></td>
<td><p>A08&#95;GLUE GlueInit Gun=1 ProgNo=1 ParaNo=1 Purge=Yes Fill=Yes 强制填充，冲洗</p></td>
</tr>
<tr>
<td rowspan="4"><p>涂胶结束指令集</p></td>
<td><p>功能</p></td>
<td><p>涂胶结束，进行测量并根据参数是否进行填充</p></td>
</tr>
<tr>
<td><p>格式</p></td>
<td><p>A08&#95;GLUE  GlueEnd  Gun=  Fill=No/Yes/ Auto注释</p></td>
</tr>
<tr>
<td><p>说明</p></td>
<td><p>&lt;参数1&gt;：功能定义；</p><p>&lt;参数2&gt;：定量机号；<strong>存外部实型变量491；</strong></p><p>&lt;参数2&gt;：填充（1不填充/2强制填充/3根据是否有请求填充）；<strong>存外部实型变量495；</strong></p><p>&lt;参数3&gt;：注释；</p></td>
</tr>
<tr>
<td><p>举例</p></td>
<td><p>A08&#95;GLUE GlueEnd Gun=1 Fill=Yes 强制填充</p></td>
</tr>
<tr>
<td rowspan="4"><p>定量机是否填满检查指令集</p></td>
<td><p>功能</p></td>
<td><p>定量机是否填满检查</p></td>
</tr>
<tr>
<td><p>格式</p></td>
<td><p>A08&#95;GLUE  GlueFillCheck  Gun=  NoCheck/Check 注释</p></td>
</tr>
<tr>
<td><p>说明</p></td>
<td><p>&lt;参数1&gt;：功能定义；</p><p>&lt;参数2&gt;：定量机号；<strong>存外部实型变量491；</strong></p><p>&lt;参数2&gt;：是否检查（1不检查/2检查）；<strong>存外部实型变量496；</strong></p><p>&lt;参数3&gt;：注释；</p></td>
</tr>
<tr>
<td><p>举例</p></td>
<td><p>A08&#95;GLUE GlueFillCheck Gun=1 Check 检查</p></td>
</tr>
<tr>
<td rowspan="4"><p>冲洗指令集</p></td>
<td><p>功能</p></td>
<td><p>冲洗指令集</p></td>
</tr>
<tr>
<td><p>格式</p></td>
<td><p>A08&#95;GLUE  GluePurge  Gun=  Purge=No/Yes/ Auto注释</p></td>
</tr>
<tr>
<td><p>说明</p></td>
<td><p>&lt;参数1&gt;：功能定义；</p><p>&lt;参数2&gt;：定量机号；存外部实型变量491；</p><p>&lt;参数2&gt;：冲洗（1不冲洗/2强制冲洗/3根据是否有请求冲洗）<strong>存外部实型变量494；</strong></p><p>&lt;参数3&gt;：注释；</p></td>
</tr>
<tr>
<td><p>举例</p></td>
<td><p>A08&#95;GLUE GluePurge Gun=1  Purge=Yes 强制冲洗</p></td>
</tr>
<tr>
<td rowspan="4"><p>定量机填充指令集</p></td>
<td><p>功能</p></td>
<td><p>定量机填充</p></td>
</tr>
<tr>
<td><p>格式</p></td>
<td><p>A08&#95;GLUE  GlueFill  Gun=  Fill=No/Yes/ Auto 注释</p></td>
</tr>
<tr>
<td><p>说明</p></td>
<td><p>&lt;参数1&gt;：功能定义；</p><p>&lt;参数2&gt;：定量机号；存外部实型变量491；</p><p>&lt;参数3&gt;：填充（1不填充/2强制填充/3根据是否有请求填充）；<strong>存外部实型变量495；</strong></p><p>&lt;参数4&gt;：注释；</p></td>
</tr>
<tr>
<td><p>举例</p></td>
<td><p>A08&#95;GLUE GlueFill Gun=1 Fill=Yes 强制填充</p></td>
</tr>
<tr>
<td rowspan="4"><p>设置涂胶系统指令集</p></td>
<td><p>功能</p></td>
<td><p>设置涂胶系统</p></td>
</tr>
<tr>
<td><p>格式</p></td>
<td><p>A08&#95;GLUE GlueSetSysNum  SysNum=  注释</p></td>
</tr>
<tr>
<td><p>说明</p></td>
<td><p>&lt;参数1&gt;：功能定义；</p><p>&lt;参数2&gt;：涂胶系统；<strong>存外部实型变量497；</strong></p><p>&lt;参数3&gt;：注释；</p></td>
</tr>
<tr>
<td><p>举例</p></td>
<td><p>A08&#95;GLUE GlueSetSysNum SysNum=1涂胶系统</p></td>
</tr>
</table>
<tr>
<td rowspan="4"><p>涂胶结束指令集</p></td>
<td><p>功能</p></td>
<td><p>涂胶结束，进行测量并根据参数是否进行填充</p></td>
</tr>

[E3] {'key': '06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂胶应用操作手册》(A-1)/SX322012《新松机器人涂胶应用操作手册》(A-1)', 'profile': '4.0', 'revision': 'V5.0 / A-1', 'category': 'adhesive_dispensing'} | /d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂胶应用操作手册》(A-1)/SX322012《新松机器人涂胶应用操作手册》(A-1).md | lines 784-877 | 8367b5b11b1bfc36e27dddffd13b8dfccc9b8c764063b98b40e1cabec938c0c7
<table>
<tr>
<td><p>NOP   </p></td>
<td></td>
</tr>
<tr>
<td><p>IF   IN&#35;38=ON GOTO L101</p></td>
<td><p>判断胶机模式是否为模拟</p></td>
</tr>
<tr>
<td><p>IF   I498 &lt;&gt;0 GOTO L101</p></td>
<td><p>判断机器人模式（NORMAL，SIM，DRY）</p></td>
</tr>
<tr>
<td><p>WAIT   IN&#35;65=ON T=&#45;1&#46;0</p></td>
<td><p>等待自动模式</p></td>
</tr>
<tr>
<td><p>OUT   OT&#35;46=ON</p></td>
<td><p>系统接通信号置ON</p></td>
</tr>
<tr>
<td><p>OUT   OT&#35;40=ON</p></td>
<td><p>运行许可信号置ON</p></td>
</tr>
<tr>
<td><p>PULSE   OT&#35;47 =ON T=0&#46;1</p></td>
<td><p>再触发加热器</p></td>
</tr>
<tr>
<td><p>WAIT   IN&#35;72=ON T=&#45;1&#46;0</p></td>
<td><p>等待加热器/泵无故障</p></td>
</tr>
<tr>
<td><p>WAIT   IN&#35;68=ON T=&#45;1&#46;0</p></td>
<td><p>等待加热器接通</p></td>
</tr>
<tr>
<td><p>WAIT   IN&#35;69=ON T=&#45;1&#46;0</p></td>
<td><p>等待加热器准备就绪</p></td>
</tr>
<tr>
<td><p>PULSE   OT&#35;48 =ON T=0&#46;1</p></td>
<td><p>再触发泵</p></td>
</tr>
<tr>
<td><p>WAIT   IN&#35;66=ON T=&#45;1&#46;0</p></td>
<td><p>等待泵接通</p></td>
</tr>
<tr>
<td><p>CALL   GLUEPURGE</p></td>
<td><p>调用冲洗指令集</p></td>
</tr>
<tr>
<td><p>CALL   GLUEFILL</p></td>
<td><p>调用填充指令集</p></td>
</tr>
<tr>
<td><p>OUT   OG&#35;1 =I492</p></td>
<td><p>输出程序号至胶机</p></td>
</tr>
<tr>
<td><p>WAIT   IG&#35;1 ==I492 T=&#45;1&#46;0</p></td>
<td><p>等待胶机反馈程序号结果</p></td>
</tr>
<tr>
<td><p>OUT   OG&#35;2 =I493</p></td>
<td><p>输出参数号至胶机</p></td>
</tr>
<tr>
<td><p>WAIT   IG&#35;2 ==I493 T=&#45;1&#46;0</p></td>
<td><p>等待胶机反馈参数号结果</p></td>
</tr>
<tr>
<td><p>OUT   OT&#35;33=ON</p></td>
<td><p>启动</p></td>
</tr>
<tr>
<td><p>WAIT   IN&#35;48=ON T=&#45;1&#46;0</p></td>
<td><p>等待涂胶准备就绪信号</p></td>
</tr>
<tr>
<td><p>   L101</p></td>
<td></td>
</tr>
<tr>
<td><p>RET   </p></td>
<td></td>
</tr>
<tr>
<td><p>END   </p></td>
<td></td>
</tr>
</table>

[E4] {'key': '06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂胶应用操作手册》(A-1)/SX322012《新松机器人涂胶应用操作手册》(A-1)', 'profile': '4.0', 'revision': 'V5.0 / A-1', 'category': 'adhesive_dispensing'} | /d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂胶应用操作手册》(A-1)/SX322012《新松机器人涂胶应用操作手册》(A-1).md | lines 384-387 | bc3b4dbcf1e29175d743d79585042e8b8627f02152de7818d9f7b32e22b106dd
<tr>
<td><p>举例</p></td>
<td><p>A08&#95;GLUE GlueInit Gun=1 ProgNo=1 ParaNo=1 Purge=Yes Fill=Yes 强制填充，冲洗</p></td>
</tr>
[{"caption": "", "colspan": 1, "column": 1, "id": "35.row.4.cell.1", "images": [], "inherited": true, "is_header": false, "line_end": 387, "line_start": 371, "parent_id": "35.row.4", "rowspan": 4, "source_file": "/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂胶应用操作手册》(A-1)/SX322012《新松机器人涂胶应用操作手册》(A-1).md", "source_row": 1, "text": "涂胶初始化指令集", "type": "table_cell"}]

[E5] {'key': '06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂胶应用操作手册》(A-1)/SX322012《新松机器人涂胶应用操作手册》(A-1)', 'profile': '4.0', 'revision': 'V5.0 / A-1', 'category': 'adhesive_dispensing'} | /d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂胶应用操作手册》(A-1)/SX322012《新松机器人涂胶应用操作手册》(A-1).md | lines 469-472 | 468d1b33a0f58e044ed6fcd4bb307145dc9f67bfc31b4d9f9f5f2e4294a16dd9
<tr>
<td><p>举例</p></td>
<td><p>A08&#95;GLUE GlueSetSysNum SysNum=1涂胶系统</p></td>
</tr>
[{"caption": "", "colspan": 1, "column": 1, "id": "35.row.24.cell.1", "images": [], "inherited": true, "is_header": false, "line_end": 472, "line_start": 456, "parent_id": "35.row.24", "rowspan": 4, "source_file": "/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂胶应用操作手册》(A-1)/SX322012《新松机器人涂胶应用操作手册》(A-1).md", "source_row": 21, "text": "设置涂胶系统指令集", "type": "table_cell"}]

[E6] {'key': '06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂胶应用操作手册》(A-1)/SX322012《新松机器人涂胶应用操作手册》(A-1)', 'profile': '5.0', 'revision': 'V5.0 / A-1', 'category': 'adhesive_dispensing'} | /d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂胶应用操作手册》(A-1)/SX322012《新松机器人涂胶应用操作手册》(A-1).md | lines 784-877 | 956004adc193d9a5394c2a5d13ce56f1f559bc365df480c9bb5dfb0aa5fecfee


[E7] {'key': '06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂胶应用操作手册》(A-1)/SX322012《新松机器人涂胶应用操作手册》(A-1)', 'profile': '5.0', 'revision': 'V5.0 / A-1', 'category': 'adhesive_dispensing'} | /d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂胶应用操作手册》(A-1)/SX322012《新松机器人涂胶应用操作手册》(A-1).md | lines 298-350 | 99f2a2d92483e7d2e609465d724648056157d64832e8c96af429534e9fd8f6c5
<table>
<tr>
<td rowspan="4"><p>开胶枪指令</p></td>
<td><p>功能</p></td>
<td><p>开胶枪</p></td>
</tr>
<tr>
<td><p>格式</p></td>
<td><p>GLUEL  P  VL=  ACC=  CNT=  ET=  INTERLOCK=  GLUEON  GUN=  CALIB=  PARANo =  TIME/DIS= </p></td>
</tr>
<tr>
<td><p>说明</p></td>
<td><p>&lt;参数1&gt;：点位；</p><p>&lt;参数2&gt;：速度；</p><p>&lt;参数3&gt;：加速度；</p><p>&lt;参数4&gt;：逼近值；</p><p>&lt;参数5&gt;：外部工具；</p><p>&lt;参数6&gt;：内部锁定；</p><p>&lt;参数7&gt;：功能定义；</p><p>&lt;参数8&gt;：定量机；</p><p>&lt;参数9&gt;：涂胶参数文件号；</p><p>&lt;参数10&gt;：参数号（发给胶机的）；</p><p>&lt;参数11&gt;：提前开胶时间/距离（负值提前，正值滞后）；</p></td>
</tr>
<tr>
<td><p>举例</p></td>
<td><p>GLUEL  P1 VL=300 ACC=100 CNT=10 ET=1 INTERLOCK=1 GLUEON GUN=1 CALIB=1 PARANo =1 TIME =20 </p></td>
</tr>
<tr>
<td rowspan="4"><p>关胶枪指令</p></td>
<td><p>功能</p></td>
<td><p>关胶枪</p></td>
</tr>
<tr>
<td><p>格式</p></td>
<td><p>GLUEL  P  VL=  ACC=  CNT=  ET=  INTERLOCK=  GLUEOFF  TIME/DIS=</p></td>
</tr>
<tr>
<td><p>说明</p></td>
<td><p>&lt;参数1&gt;：点位；</p><p>&lt;参数2&gt;：速度；</p><p>&lt;参数3&gt;：加速度；</p><p>&lt;参数4&gt;：逼近值；</p><p>&lt;参数5&gt;：外部工具；</p><p>&lt;参数6&gt;：内部锁定；</p><p>&lt;参数7&gt;：功能定义；</p><p>&lt;参数8&gt;：提前关胶时间/距离（负值提前，正值滞后）；</p></td>
</tr>
<tr>
<td><p>举例</p></td>
<td><p>GLUEL  P1 VL=300 ACC=100 CNT=10 ET=1 INTERLOCK=1 GLUEOFF TIME=20</p></td>
</tr>
<tr>
<td rowspan="4"><p>切换参数指令</p></td>
<td><p>功能</p></td>
<td><p>切换参数</p></td>
</tr>
<tr>
<td><p>格式</p></td>
<td><p>GLUEL  P  VL=  ACC=  CNT=  ET=  GLUESWITCH  CALIB= </p><p>PARANo =  TIME/DIS=</p></td>
</tr>
<tr>
<td><p>说明</p></td>
<td><p>&lt;参数1&gt;：点位；</p><p>&lt;参数2&gt;：速度；</p><p>&lt;参数3&gt;：加速度；</p><p>&lt;参数4&gt;：逼近值；</p><p>&lt;参数5&gt;：外部工具；</p><p>&lt;参数6&gt;：内部锁定；</p><p>&lt;参数7&gt;：功能定义；</p><p>&lt;参数8&gt;：涂胶参数文件号；</p><p>&lt;参数9&gt;：参数号（发给胶机的）；</p><p>&lt;参数10&gt;：提前切换参数时间/距离（负值提前，正值滞后）； </p></td>
</tr>
<tr>
<td><p>举例</p></td>
<td><p>GLUEL  P1 VL=300 ACC=100 CNT=10 ET=1 INTERLOCK=1 GLUESWITCH CALIB =1 PARANo =2  TIME =10</p></td>
</tr>
</table>

[E8] {'key': '06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂胶应用操作手册》(A-1)/SX322012《新松机器人涂胶应用操作手册》(A-1)', 'profile': '4.0', 'revision': 'V5.0 / A-1', 'category': 'adhesive_dispensing'} | /d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂胶应用操作手册》(A-1)/SX322012《新松机器人涂胶应用操作手册》(A-1).md | lines 376-379 | 846e243eb9a5817043700c17954e434f661719d847523c20a817c56b50c296c5
<tr>
<td><p>格式</p></td>
<td><p>A08&#95;GLUE GlueInit Gun= ProgNo= ParaNo= Purge=No/Yes/Auto  Fill=No/Yes/ Auto注释</p></td>
</tr>
[{"caption": "", "colspan": 1, "column": 1, "id": "35.row.2.cell.1", "images": [], "inherited": true, "is_header": false, "line_end": 379, "line_start": 371, "parent_id": "35.row.2", "rowspan": 4, "source_file": "/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂胶应用操作手册》(A-1)/SX322012《新松机器人涂胶应用操作手册》(A-1).md", "source_row": 1, "text": "涂胶初始化指令集", "type": "table_cell"}]
Omitted: []

## Retrieved content summary and coding answer

Always display a source-attributed summary of the found objects, even when their content cannot support the requested code. The summary uses stored object summaries and remains available if generation fails. With no hits, explicitly report that no relevant indexed content was found.

The coding answer ends with a meaningful fenced code snippet for the selected category, integrating the instruction requested in the question. Its source citations, corpus/revision, and required placeholders appear directly before the code block. If the evidence cannot support such an example, the answer explains the missing information.

A rich example includes a concrete scenario, environment and initial values, expected outcome, and a final multi-statement code block with setup, the requested instruction, and follow-up. The shared RAG class validates structured generation and retries once if incomplete. If evidence cannot support the surrounding code, it explains the missing context. After updating the shared module, restart the kernel and rerun configuration and client setup to load the new implementation.

Each selected case reuses the **exact evidence from the preceding retrieval pass**
through the production answer method, avoiding a second embedding request or a
different retrieval result. It displays a retrieved-content summary and answer for
every case; generation failures retain the available summary. Completed answers
remain in `coverage_answer_results` if execution is interrupted.

The coding-answer validator may return `unsupported` for GUI or workflow
questions, which is separate from retrieval coverage. Review the explanation and
sources. A structurally `included` example still requires source checking.

In [8]:
# | notest
coverage_answer_results, coverage_answer_errors = {}, {}
coverage_answer_metrics = await run_coverage_answers(
    app, coverage_cases, top_k=COVERAGE_TOP_K,
    retrieval_results=coverage_retrieval_results, retrieval_errors=coverage_retrieval_errors,
    results=coverage_answer_results, errors=coverage_answer_errors)
display(coverage_answer_metrics[
    ['case_id', 'category', 'hits', 'context_chars', 'omissions', 'missing_manuals', 'example_status', 'error']])

## [1/17] category_adhesive_dispensing

如何按涂胶手册配置胶机并编写一次涂胶流程，包含开始出胶、沿轨迹涂胶和停止出胶？请说明工艺文件和IO的准备条件。

### Retrieved content summary

- 该表展示了一段机器人涂胶程序的完整流程，按行顺序定义了**坐标系/负载配置**、**运动路径**、**涂胶控制**及**程序终止**四个阶段：

1.  **初始化设置**：
    *   设置用户坐标系（`SET UF #0`）和工具坐标系（`SET TF #1`）。
    *   定义负载为“抓手加车架”（`PAYLOAD #1`）。

2.  **定位与准备**：
    *   快速移动至“冲锋位”（`PR102`）及过渡点 `P1`。
    *   初始化涂胶系统：设置系统编号为1（`GlueSetSysNum`），并对1号胶枪执行初始化，包括冲洗和填充（`GlueInit`）。

3.  **涂胶执行**：
    *   线性移动至涂胶起点 `P4`。
    *   **开胶**：在 `P1` 执行 `GLUEL` 指令，开启1号胶枪，进行校准和涂胶（持续20ms）。
    *   **关胶**：执行 `GLUEL` 指令，关闭1号胶枪（停止时间20ms）。
    *   线性返回至 `P4`。

4.  **收尾与结束**：
    *   结束涂胶循环（`GlueEnd`）。
    *   执行胶枪填充检查（`GlueFillCheck`）。
    *   快速移动至点 `P2`，再返回“冲锋位”（`PR102`）。
    *   程序返回（`RET`）并结束（`END`）。

**核心结构**：表格共19行，前两列分别为**指令代码**和**功能说明/注释**，无合并单元格，逻辑清晰，涵盖了从系统配置、安全定位、胶枪初始化、精确涂胶动作到安全复位的全自动化涂胶工序。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂胶应用操作手册》(A-1)/SX322012《新松机器人涂胶应用操作手册》(A-1).md`, lines 701–778; corpus 5.0, revision V5.0 / A-1; object `37c4f5108de3bb61e98ae85067745cd52c511dea5e3d0119a6a9619c1525326f`.

- 涂胶结束指令集功能：涂胶结束，进行测量并根据参数是否进行填充
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂胶应用操作手册》(A-1)/SX322012《新松机器人涂胶应用操作手册》(A-1).md`, lines 388–392; corpus 4.0, revision V5.0 / A-1; object `ad90fdf2195c5a0665d2ed14a835fb0bc4d3e070ab3f50b3d900862f07b0f2ce`.

- 该表格展示了一段机器人涂胶应用的 PLC 控制逻辑，主要流程为：**前置条件校验 -> 系统初始化与硬件准备 -> 胶机配置与启动**。具体步骤如下：

1.  **模式与状态检查**：首先判断胶机是否处于模拟模式（`IN#38`）及机器人模式（`I498`），若不符合要求则跳转至结束标签 `L101`；随后等待进入自动模式（`IN#65`）。
2.  **系统接通与硬件触发**：置位系统接通（`OT#46`）和运行许可（`OT#40`）信号；触发加热器（`OT#47`）并等待其无故障（`IN#72`）、接通（`IN#68`）及就绪（`IN#69`）；触发泵（`OT#48`）并等待其接通（`IN#66`）。
3.  **胶路预处理与配置**：调用冲洗（`GLUEPURGE`）和填充（`GLUEFILL`指令集，并输出程序号（`OG#1`=I492）与参数号（`OG#2`=I493）至胶机，分别等待胶机反馈确认。
4.  **启动执行**：发出启动信号（`OT#33`）并等待涂胶准备就绪信号（`IN#48`），最后通过 `RET` 和 `END` 结束程序。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂胶应用操作手册》(A-1)/SX322012《新松机器人涂胶应用操作手册》(A-1).md`, lines 784–877; corpus 4.0, revision V5.0 / A-1; object `8367b5b11b1bfc36e27dddffd13b8dfccc9b8c764063b98b40e1cabec938c0c7`.

- 涂胶初始化指令集举例：A08_GLUE GlueInit Gun=1 ProgNo=1 ParaNo=1 Purge=Yes Fill=Yes 强制填充，冲洗
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂胶应用操作手册》(A-1)/SX322012《新松机器人涂胶应用操作手册》(A-1).md`, lines 384–387; corpus 4.0, revision V5.0 / A-1; object `bc3b4dbcf1e29175d743d79585042e8b8627f02152de7818d9f7b32e22b106dd`.

- 在“设置涂胶系统指令集”模块下，该行为示例条目，展示了设置涂胶系统的指令格式：`A08_GLUE GlueSetSysNum SysNum=1涂胶系统`。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂胶应用操作手册》(A-1)/SX322012《新松机器人涂胶应用操作手册》(A-1).md`, lines 469–472; corpus 4.0, revision V5.0 / A-1; object `468d1b33a0f58e044ed6fcd4bb307145dc9f67bfc31b4d9f9f5f2e4294a16dd9`.

- 该表格展示了一段用于控制胶涂覆系统的梯形图或逻辑指令序列，主要执行流程包括：

1.  **模式检查与跳转**：首先检查胶机是否处于模拟模式（IN#38）或机器人是否处于非正常模式（I498），若满足条件则跳转至标签 L101 结束流程。
2.  **启动准备**：等待自动模式（IN#65），随后置位系统接通（OT#46）和运行许可（OT#40）信号。
3.  **硬件预启与状态确认**：脉冲触发加热器（OT#47）和泵（OT#48），并依次等待加热器/泵无故障、接通、准备就绪以及泵接通信号。
4.  **核心工艺执行**：调用冲洗（GLUEPURGE）和填充（GLUEFILL）指令集。
5.  **参数交互与启动**：向胶机输出程序号（OG#1/I492）和参数号（OG#2/I493）并等待反馈确认，最后置位启动信号（OT#33）并等待涂胶准备就绪信号（IN#48）。
6.  **流程结束**：跳转至标签 L101，执行返回（RET）和结束（END）指令。

整体逻辑为：在确认系统处于自动模式且安全无故障后，初始化硬件，执行胶水准备动作，同步程序参数，并最终启动涂胶流程。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂胶应用操作手册》(A-1)/SX322012《新松机器人涂胶应用操作手册》(A-1).md`, lines 784–877; corpus 5.0, revision V5.0 / A-1; object `956004adc193d9a5394c2a5d13ce56f1f559bc365df480c9bb5dfb0aa5fecfee`.

- 该表格定义了三种**GLUEL** 涂胶控制指令，分别对应不同的胶枪状态操作。各指令结构相似，均包含基础运动参数（点位、速度、加速度、逼近值、工具/锁定配置）及特定的功能与时序参数。摘要如下：

1.  **开胶枪指令 (GLUEON)**
    *   **功能**：启动胶枪。
    *   **关键参数**：在基础参数基础上，包含 `GUN`（定量机）、`PARANo`（涂胶参数文件号）及 `TIME/DIS`（提前开胶时间/距离，负值提前，正值滞后）。
    *   **示例**：`GLUEL P1 VL=300 ... GLUEON GUN=1 ... TIME=20`

2.  **关胶枪指令 (GLUEOFF)**
    *   **功能**：停止胶枪。
    *   **关键参数**：结构较简，主要包含基础参数及 `TIME/DIS`（提前关胶时间/距离，负值提前，正值滞后）。
    *   **示例**：`GLUEL P1 VL=300 ... GLUEOFF TIME=20`

3.  **切换参数指令 (GLUESWITCH)**
    *   **功能**：切换涂胶参数。
    *   **关键参数**：包含基础参数、`PARANo`（新参数文件号）及 `TIME/DIS`（提前切换时间/距离，负值提前，正值滞后）。
    *   **示例**：`GLUEL P1 VL=300 ... GLUESWITCH ... PARANo=2 TIME=10`

**通用说明**：
*   所有指令均通过 `VL`（速度）、`ACC`（加速度）、`CNT`（逼近值）控制运动过程。
*   `TIME/DIS` 参数用于精确控制动作触发时机，支持基于时间或距离的提前/滞后调整。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂胶应用操作手册》(A-1)/SX322012《新松机器人涂胶应用操作手册》(A-1).md`, lines 298–350; corpus 5.0, revision V5.0 / A-1; object `99f2a2d92483e7d2e609465d724648056157d64832e8c96af429534e9fd8f6c5`.

- 涂胶初始化指令集：格式为 `A08_GLUE GlueInit Gun= ProgNo= ParaNo= Purge=No/Yes/Auto Fill=No/Yes/ Auto`。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322012《新松机器人涂胶应用操作手册》(A-1)/SX322012《新松机器人涂胶应用操作手册》(A-1).md`, lines 376–379; corpus 4.0, revision V5.0 / A-1; object `846e243eb9a5817043700c17954e434f661719d847523c20a817c56b50c296c5`.

### Coding or diagnostic answer

按涂胶手册（SX322012 V5.0/A-1）配置胶机并编写一次涂胶流程需分三步：

一、工艺文件与IO准备条件（E3）：
- 确认胶机非模拟模式（IN#38≠ON）且机器人处于NORMAL模式（I498=0）；
- 等待自动模式信号 IN#65=ON；
- 置ON系统接通信号 OT#46 和运行许可信号 OT#40；
- 触发加热器（PULSE OT#47），等待加热器无故障 IN#72、接通 IN#68、就绪 IN#69；
- 触发泵（PULSE OT#48），等待泵接通 IN#66；
- 调用冲洗（CALL GLUEPURGE）和填充（CALL GLUEFILL）；
- 通过 OG#1/OG#2 输出程序号（I492）和参数号（I493）至胶机，并等待 IG#1/IG#2 反馈一致；
- 发出启动信号 OT#33=ON，等待涂胶准备就绪 IN#48=ON。

二、胶机配置（E1、E2、E5）：
- 用 A08_GLUE GlueSetSysNum SysNum=1 选择涂胶系统（存外部实型变量497）；
- 用 A08_GLUE GlueInit Gun=1 ProgNo=1 ParaNo=1 Purge=Yes Fill=Yes 完成初始化，其中 ProgNo 存变量492、ParaNo 存变量493、Purge 存变量494、Fill 存变量495。

三、涂胶流程（E1、E7）：
- 开胶：GLUEL P1 VL=300 ACC=100 CNT=10 ET=1 GLUEON GUN=1 CALIB=1 PARANo=1 TIME=20，沿点位P1线性运动同时开启1号胶枪，TIME=20表示提前20ms开胶；
- 沿轨迹涂胶：在GLUEON与GLUEOFF之间可插入多段MOVL/GLUEL指令完成轨迹；
- 关胶：GLUEL P1 VL=300 ACC=100 CNT=10 ET=1 GLUEOFF TIME=20，到达终点后关闭胶枪；
- 结束：A08_GLUE GlueEnd Gun=1 Fill=No 进行测量，GlueFillCheck Gun=1 Check 检查定量机是否填满。

### Example — adhesive_dispensing

在Siasun机器人涂胶工作站上，操作员需为1号定量胶机配置工艺参数（程序号1、参数号1），完成一次从冲锋位出发、沿P4→P1轨迹涂胶、再返回冲锋位的完整循环。

**Environment and prerequisites:** 前置条件：胶机加热器与泵已通电且无故障（IN#72/IN#68/IN#69/IN#66均为ON）；系统接通OT#46与运行许可OT#40已置ON；程序号I492=1、参数号I493=1已通过OG#1/OG#2下发并获IG#1/IG#2确认；涂胶准备就绪IN#48=ON。变量：SysNum=1, Gun=1, ProgNo=1, ParaNo=1, Purge=Yes, Fill=Yes, VL=300, ACC=100, CNT=10, ET=1, CALIB=1, TIME=20。点位：PR102为冲锋位，P4为涂胶起点，P1为涂胶终点。

**Expected result:** 机器人从冲锋位PR102运动至涂胶起点P4，再沿P1方向以300mm/s线性运动；到达P1时1号胶枪提前20ms开启出胶，运动结束后20ms关闭胶枪；随后机器人返回P4和冲锋位PR102，胶机执行测量与填充检查，完成一次涂胶循环。

**Manual:** SX322012《新松机器人涂胶应用操作手册》(A-1) V5.0 [E1] [E2] [E3] [E5] [E7]

```text
SET UF #0
SET TF #1
PAYLOAD #1
MOVJ PR102 VJ=30.0 ACC=30 CNT=0
A08_GLUE GlueSetSysNum SysNum=1
A08_GLUE GlueInit Gun=1 ProgNo=1 ParaNo=1 Purge=Yes Fill=Yes
MOVL P4 VL=1000.0 ACC=100 CNT=30 ET=1
GLUEL P1 VL=300 ACC=100 CNT=10 ET=1 GLUEON GUN=1 CALIB=1 PARANo=1 TIME=20
GLUEL P1 VL=300 ACC=100 CNT=10 ET=1 GLUEOFF TIME=20
MOVL P4 VL=1000.0 ACC=100 CNT=30 ET=1
A08_GLUE GlueEnd Gun=1 Fill=No
A08_GLUE GlueFillCheck Gun=1 Check
MOVJ PR102 VJ=30.0 ACC=30 CNT=0
RET
END
```

## [2/17] category_arc_welding

如何使用ARCON开始弧焊、沿焊缝运动并用ARCOFF结束焊接？请说明起弧文件与焊接文件的区别。

### Retrieved content summary

- ARCON #1 #2：指定起弧与焊接文件，其中文件#1为起弧文件，文件#2为焊接文件。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322003《新松机器人弧焊应用操作手册》(B-5)/SX322003《新松机器人弧焊应用操作手册》(B-5).md`, lines 12682–12685; corpus 4.0, revision V5.0 / B-5; object `76dbdbbe2784fa3f5ff11ade3d77a97bceb732f77591ccbf2d15f5589cf8132d`.

- ARCON [1] [1]：以起弧文件1起弧，焊接文件1焊接。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322003《新松机器人弧焊应用操作手册》(C-1)/SX322003《新松机器人弧焊应用操作手册》(C-1).md`, lines 2781–2784; corpus 5.0, revision V5.0 / C-1; object `215eaf15ab496c036b2ceb8d3c2651de78dc1e042c8d2e2f8aaf2b0af27133aa`.

- 指令 `ARCON #1 #2`：参数 #1 指定起弧文件，参数 #2 指定焊接文件。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322003《新松机器人弧焊应用操作手册》(B-5)/SX322003《新松机器人弧焊应用操作手册》(B-5).md`, lines 4631–4634; corpus 4.0, revision V5.0 / B-5; object `01ba11f79a0af26702faff35a502f50807d0a43a13a2eabbf77776e1d8b55bbe`.

- ARCON #1 #2 参数定义中，文件#1指定为起弧文件，文件#2指定为焊接文件。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322003《新松机器人弧焊应用操作手册》(B-5)/SX322003《新松机器人弧焊应用操作手册》(B-5).md`, lines 13848–13851; corpus 4.0, revision V5.0 / B-5; object `af5b6f3473b353ae04f105b8a3d8aeed2ff3eb9c3ffbfb9effd6df5036e559c9`.

- **指令参数 `ARCON #1 #2` 说明：#1 指定起弧文件1，#2 指定焊接文件2。**
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322003《新松机器人弧焊应用操作手册》(B-5)/SX322003《新松机器人弧焊应用操作手册》(B-5).md`, lines 8797–8800; corpus 4.0, revision V5.0 / B-5; object `994fc47187cd47a831e1c1e76006557858e1705a298d2ded314db327701378db`.

- ARCON 指令用于执行起弧操作，需同时指定起弧文件号 [1] 和焊接文件号 [1]。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322003《新松机器人弧焊应用操作手册》(C-1)/SX322003《新松机器人弧焊应用操作手册》(C-1).md`, lines 5797–5800; corpus 5.0, revision V5.0 / C-1; object `a578110d80af410d7b4f99e16d3ec5d518042d738c3ec0d980c8c2c45e3bcd2c`.

- 指令 `ARCON #1 #2`：文件#1 为起弧文件，文件 2 为焊接文件。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322003《新松机器人弧焊应用操作手册》(B-5)/SX322003《新松机器人弧焊应用操作手册》(B-5).md`, lines 8960–8963; corpus 4.0, revision V5.0 / B-5; object `7c364c3924f7ca3c3771092d2cd89e29c28c2a44b98ddfd5005089006f18ca7c`.

- ARCON #1 #2：起弧/文件#1为起弧文件；文件#2为焊接文件
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322003《新松机器人弧焊应用操作手册》(B-5)/SX322003《新松机器人弧焊应用操作手册》(B-5).md`, lines 11890–11893; corpus 4.0, revision V5.0 / B-5; object `0b17944df06d5eb33366b76060f2a6775cca0ded889320ed03f08cc1429bc785`.

### Coding or diagnostic answer

ARCON指令用于起弧，其语法为 ARCON #起弧文件 #焊接文件。第一个参数（起弧文件）定义电弧引燃阶段的参数（如电流爬升曲线、引弧时间等），第二个参数（焊接文件）定义焊接过程中的稳态参数（如焊接电流、电压、速度等）。ARCOFF #收弧文件 用于收弧，其参数定义熄弧阶段的电流衰减曲线。区别在于：起弧文件控制

### Example — arc_welding

单道弧焊任务：机器人从安全点移动到焊缝起点P3，使用起弧文件#1引燃电弧并切换到焊接文件#2的稳态参数，以焊接速度沿焊缝直线运动至终点P4，最后使用收弧文件#1熄弧。

**Environment and prerequisites:** 前提条件：控制器中已配置起弧文件#1（定义引弧电流爬升参数）、焊接文件#2（定义稳态焊接电流/电压）、收弧文件#1（定义熄弧电流衰减参数）；位置点P3（焊缝起点）和P4（焊缝终点）已示教；接近速度VL=50，焊接速度VL=8，加速度ACC=100，CNT=0。

**Expected result:** 机器人以VL=50线性运动至P3后，调用起弧文件#1的参数引燃电弧，随即切换至焊接文件#2的稳态焊接参数；以VL=8沿焊缝直线运动至P4；到达P4后调用收弧文件#1的参数完成熄弧，电弧熄灭。

**Manual:** SX322003《新松机器人弧焊应用操作手册》V5.0/B-5 [E1] [E3] [E5]

```text
ARCL P3 VL = 50 ACC = 100 CNT = 0
ARCON #1 #2
ARCL P4 VL = 8 ACC = 100 CNT = 0
ARCOFF #1
```

## [3/17] category_fds

如何按FDS手册配置主机工作参数和IO，并组织一次FDS作业的启动、完成状态确认及后续动作？

### Retrieved content summary

- FDS初始化指令的格式为：`A14_FDS Init Gun =(参数1) Count=(参数2) ;注释内容`
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322016《新松机器人FDS应用操作手册》(A-1)/SX322016《新松机器人FDS应用操作手册》(A-1).md`, lines 281–284; corpus 4.0, revision V5.0 / A-1; object `b29c7e1b3b45a2c03b51ba2697aaeee8bc68f25c46c6172b9f577e910890bb71`.

- **FDS初始化指令（格式）**：`A14_FDS Init Gun =(参数1) Count=(参数2) ;注释内容`
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322016《新松机器人FDS应用操作手册》(A-1)/SX322016《新松机器人FDS应用操作手册》(A-1).md`, lines 281–284; corpus 5.0, revision V5.0 / A-1; object `3f3711a16a4b7b8a6d66542c2fdc1fba97a9b691e238be4e58e0ea3a86d88798`.

- FDS初始化指令示例：`A14_FDS Init Gun=2 Count=3`，表示设置焊枪2的防漏焊检测数量为3。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322016《新松机器人FDS应用操作手册》(A-1)/SX322016《新松机器人FDS应用操作手册》(A-1).md`, lines 289–292; corpus 5.0, revision V5.0 / A-1; object `681235396a8cde29123fe59bb504138e0bfc7ffe5bbca1d09283eccb82f2f5a7`.

- **FDS防漏铆检测指令 - 功能**：FDS 标定运行功能指令，通过标准化流程对设备或机器人执行工艺参数的验证和调整，以确保生产过程中设备性能的稳定性和一致性。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322016《新松机器人FDS应用操作手册》(A-1)/SX322016《新松机器人FDS应用操作手册》(A-1).md`, lines 458–462; corpus 4.0, revision V5.0 / A-1; object `4b883809818ddae85b199015412ec524963f6627b32c9d8f93c3e145e0e9cf4e`.

- FDS初始化指令的功能：执行FDS初始化，并设置防漏铆检测数量。（该单元格跨4行）
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322016《新松机器人FDS应用操作手册》(A-1)/SX322016《新松机器人FDS应用操作手册》(A-1).md`, lines 276–280; corpus 4.0, revision V5.0 / A-1; object `0393c5a19e77984362341b0748be333f032bdfd61db13c1aa4832f5234432197`.

- 该行描述了“FDS初始化指令”的功能，即执行FDS初始化并设置防漏铆检测数量。其中，“FDS初始化指令”为跨4行的合并单元格，表示该属性适用于后续多行指令。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322016《新松机器人FDS应用操作手册》(A-1)/SX322016《新松机器人FDS应用操作手册》(A-1).md`, lines 276–280; corpus 5.0, revision V5.0 / A-1; object `399da97ea252e0882808e7dd73da77a57655a2e13da681f6e06b0eec175ba281`.

- **FDS初始化指令**示例：`A14_FDS Init Gun=2 Count=3`，含义为设置焊枪2的防漏焊检测数量为3。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322016《新松机器人FDS应用操作手册》(A-1)/SX322016《新松机器人FDS应用操作手册》(A-1).md`, lines 289–292; corpus 4.0, revision V5.0 / A-1; object `8e7545458acfb060289561707a8b786521b162f532aa4ee32239eb61c9ed1462`.

- 该表格行来自新松机器人FDS应用操作手册，显示：第二列为“NOP”，第三列为“开始”，第一列为空（可能继承上方合并单元格的值）。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322016《新松机器人FDS应用操作手册》(A-1)/SX322016《新松机器人FDS应用操作手册》(A-1).md`, lines 300–304; corpus 4.0, revision V5.0 / A-1; object `a64f0965d753dd3873a9d8bb2e55ff8204d79098a95fd786172fb7bae4eef014`.

### Coding or diagnostic answer

根据FDS应用操作手册，配置主机工作参数使用FDS初始化指令 A14_FDS Init Gun=(铆枪号) Count=(防漏铆检测数量)，其中参数1写入用户整型变量424，参数2写入用户整型变量425。FDS作业启动（标定运行）使用 A14_FDS AdjustZero 指令。完成状态确认及后续动作包括将焊接实际数量点数置0（SET I427=0），然后RET返回主作业，END结束。

### Example — fds

在机器人铆接工作站中，操作员需要为焊枪2配置防漏铆检测（检测3个铆点），执行一次FDS标定运行以验证工艺参数，标定完成后将焊接计数复位并返回主作业流程。

**Environment and prerequisites:** 前提：ATLAS控制器已连接FDS防漏铆检测模块，用户整型变量424（铆枪号）和425（检测数量）可写入，I427为焊接实际数量计数寄存器。初始值：I427可能残留上一次作业的计数值。用户指定铆枪号为2，防漏铆检测数量为3。

**Expected result:** FDS初始化将铆枪号2和检测数量3写入对应寄存器；AdjustZero触发标定运行流程，验证设备工艺参数；SET I427=0将焊接计数清零，确认本次作业完成状态；RET返回主作业，END结束当前子程序。

**Manual:** SX322016《新松机器人FDS应用操作手册》(A-1) V5.0 [E1] [E4] [E8]

```atlas
A14_FDS Init Gun=2 Count=3; 焊枪2，防漏焊检测数量为3
A14_FDS AdjustZero; 标定运行功能
SET I427=0; 焊接实际数量点数置0
```

## [4/17] category_grinding

如何首次配置打磨力控制器并完成标定，再设置打磨力、位移及出入刀监控，组织一次打磨作业？

### Retrieved content summary

- B2配置项为力控打磨工具（300N力控，含刀柄）。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322006《新松机器人打磨应用操作手册》（A-2)/SX322006《新松机器人打磨应用操作手册》（A-2).md`, lines 744–747; corpus 5.0, revision V5.0 / A-2; object `d4067328657b4bade50c2d7eae784d186670b22b8badc41e460ba8b69b04f928`.

- 指令 `SetForce` 用于**设置打磨力**。其参数包括：
*   **NumC (I#)**：控制器编号（1~8）；
*   **Force (R#)**：力大小（需根据标定范围确定）；
*   **T**：通讯延时设定值（当实际通讯延时超过该参数时，机器人将报警）。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322006《新松机器人打磨应用操作手册》（A-2)/SX322006《新松机器人打磨应用操作手册》（A-2).md`, lines 1476–1480; corpus 4.0, revision V5.0 / A-2; object `6e4edb4e83a26aff7078f664a2b47d9b8fe6b1875d4d48db10cc60e67a97d2da`.

- C：力控打磨工具控制器（内置柜内）
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322006《新松机器人打磨应用操作手册》（A-2)/SX322006《新松机器人打磨应用操作手册》（A-2).md`, lines 682–685; corpus 5.0, revision V5.0 / A-2; object `206af596f4a32e720922f510aa074e0bd35980d09b4d0accae41cef8adba6d8f`.

- 行B1：力控打磨工具（150N力控，三磨头配置）
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322006《新松机器人打磨应用操作手册》（A-2)/SX322006《新松机器人打磨应用操作手册》（A-2).md`, lines 715–718; corpus 4.0, revision V5.0 / A-2; object `decd9a1cacb1ac5a9799462c8eaa6cc847f438e8d70007d7643f2e5cef8d7747`.

- IN2对应“设定打磨压力”；该行继承的打磨力I/O真值表在M8412XXB触摸屏界面设置，定义如下：00:打磨力1，01:打磨力2，10:打磨力3，11:打磨力4。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322006《新松机器人打磨应用操作手册》（A-2)/SX322006《新松机器人打磨应用操作手册》（A-2).md`, lines 987–990; corpus 4.0, revision V5.0 / A-2; object `a55d3eb9d1836dd98cb027b0cba57be47aeffb611107720ee90b657b7131fbf8`.

- OUT2 输出功能为“实际打磨力监控预警”，当打磨力超过设定范围时接通；该行为空。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322006《新松机器人打磨应用操作手册》（A-2)/SX322006《新松机器人打磨应用操作手册》（A-2).md`, lines 1025–1029; corpus 5.0, revision V5.0 / A-2; object `77db53fe1f73155b7462d2d77b25f8cb51089bc9b2cbd633474aaba7348440b1`.

- `SetForce` 指令用于**设置打磨力**，包含三个参数：
1. **NumC**：控制器编号（1~8）；
2. **Force**：力的大小（需根据标定范围确定）；
3. **T**：通讯延时设定值（若实际通讯延时超过此值，机器人将报警）。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322006《新松机器人打磨应用操作手册》（A-2)/SX322006《新松机器人打磨应用操作手册》（A-2).md`, lines 1481–1483; corpus 4.0, revision V5.0 / A-2; object `58b3611a6094a645df7ffd4af5838731bb60fa0d07e8976f3d1e6543ace53379`.

- IN2 用于设定打磨压力，其对应的打磨力 I/O 真值表（00:打磨力1，01:打磨力2，10:打磨力3，11:打磨力4）在 M8412XXB 触摸屏界面上设置。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322006《新松机器人打磨应用操作手册》（A-2)/SX322006《新松机器人打磨应用操作手册》（A-2).md`, lines 987–990; corpus 5.0, revision V5.0 / A-2; object `8fbf1c47f03901c5c8a218798e6be160970ade080bfe614f80a092c67a3e9686`.

### Coding or diagnostic answer

The question asks for a complete workflow: first-time configuration of the force controller, calibration, setting grinding force/displacement/tool-in-out monitoring, and organizing a grinding operation. The retrieved evidence (E1–E8) documents the system components (robot, force tool, controller), the operational instructions (SetForce, SetMotorV, PStart, PEnd, ToggleTool, ResetMotor, SetGDRE), and the I/O signal table (IN1–IN8, OUT1–OUT8). However, the evidence does NOT contain: (1) any calibration procedure or steps for the force controller; (2) first-time configuration instructions; (3) a 'set displacement' instruction (only OUT3/OUT4 monitoring signals for displacement sensor thresholds); (4) a tool-in/tool-out monitoring setup procedure; or (5) a complete grinding program sequence. Without the calibration and first-time configuration syntax/steps, a faithful contextual example cannot be constructed.

## [5/17] category_laser_welding

激光焊作业需要哪些激光器、通讯和IO配置？如何按手册组织激光开启、焊接运动和激光关闭的程序？

### Retrieved content summary

- V1.1（2024-07-17，沙景超）：完善输入/输出IO配置；新增工艺配置、文件配置及激光焊指令说明。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322004《新松机器人激光焊应用操作手册》(A-4)/SX322004《新松机器人激光焊应用操作手册》(A-4).md`, lines 42–47; corpus 4.0, revision V5.0 / A-4; object `d905d2588a97ce16b3b5b2b191552fa2243f8ed6306232045b6c4e8333c3864c`.

- 版本 V1.1（2024-07-17，沙景超）：完善 I/O 配置；新增工艺、文件配置及激光焊指令说明。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322004《新松机器人激光焊应用操作手册》(A-4)/SX322004《新松机器人激光焊应用操作手册》(A-4).md`, lines 42–47; corpus 5.0, revision V5.0 / A-4; object `273cf480c8b60e4751e74b4576c4cfbf13139a6f971723ad8e4e8e59c94dbb69`.

- **LASERWELD ON[起弧]指令示例**：执行 `MOVJ P[1] V=20 ACC=20 CNT=0 : LASERWELDON [1] T=1.00`，即机器人以速度20、加速度20、连续模式移动至点P[1]，并在该点开启1号激光焊接源，起弧时间1.00秒。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322004《新松机器人激光焊应用操作手册》(C-0)/SX322004《新松机器人激光焊应用操作手册》(C-0).md`, lines 1024–1027; corpus 5.0, revision V5.0 / C-0; object `2786e4087f7d769a221398653f1165ff2c0e782b4cbeb89f4795db468f299a3e`.

- 激光焊指令 `LASERWELD ON[起弧]` 的指令格式为：`LASERWELDON [<参数1>] T = <参数2>`。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322004《新松机器人激光焊应用操作手册》(C-0)/SX322004《新松机器人激光焊应用操作手册》(C-0).md`, lines 1016–1019; corpus 5.0, revision V5.0 / C-0; object `3e4eaf054d1af6646e82a69f6eb5c59e6597678441db439b1e4f29fabf64d8c7`.

- 激光器就绪信号对应DI:33输入端口
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322004《新松机器人激光焊应用操作手册》(C-0)/SX322004《新松机器人激光焊应用操作手册》(C-0).md`, lines 786–789; corpus 5.0, revision V5.0 / C-0; object `d1583a39d8c7a29cd7cb965d72e9d457b9bd558bb8ce67231e2b564367bf083c`.

- 该表格行（第4行）描述了激光焊接程序中的一个指令及其功能：
*   **指令**：`MOVJP[3]V=20ACC=20CNT=0:LASERWELDON[1]T=1.00`
*   **含义**：设置**焊接起点**。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322004《新松机器人激光焊应用操作手册》(C-0)/SX322004《新松机器人激光焊应用操作手册》(C-0).md`, lines 1096–1099; corpus 5.0, revision V5.0 / C-0; object `eef3f7176f885da786bb1fa89977789c0f7fd80928afbae7456e53de24fb681f`.

- 焊接起点指令：`LASERL P3 VL=100.0 ACC=100 CNT=0 LASERON FILE=1 T=0.000`
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322004《新松机器人激光焊应用操作手册》(A-4)/SX322004《新松机器人激光焊应用操作手册》(A-4).md`, lines 1125–1128; corpus 5.0, revision V5.0 / A-4; object `b51abd0c5234e8b2ed19ae61ee1b03b9ddda0ee8e5c1c13b6dabfd45549cc04e`.

- 激光器就绪对应的DI信号点为DI:33
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322004《新松机器人激光焊应用操作手册》(A-4)/SX322004《新松机器人激光焊应用操作手册》(A-4).md`, lines 789–792; corpus 5.0, revision V5.0 / A-4; object `8ea26d9f2d349bee23c85edc181c7904d449ca9959e3bf55984d5fa283fed91b`.

### Coding or diagnostic answer

根据新松机器人激光焊应用操作手册（V5.0 / C-0），激光焊作业需要以下配置：

1. **IO配置**（E5/E8）：
   - 数字输出(DO)：工艺号1-4（DO:201-204）、激光使能（DO:41）、调制使能（DO:44）、保护气（DO:49）、摆动使能（DO:46）、故障复位（DO:52）、粘丝检测（DO:47）、送丝使能（DO:42）、送气使能（DO:43）、手动送丝（DO:50）、手动退丝（DO:51）
   - 模拟输出(GO)：激光功率（GO:1）、送丝速度（GO:2）、摆动频率（GO:3）、摆动宽度（GO:4）、摆动高度（GO:5）、旋转角度（GO:6）、回抽长度（GO:7）、补丝长度（GO:8）
   - 数字输入(DI)：激光器就绪（DI:33）、出光状态（DI:41）、粘丝检测（DI:46）
   - 模拟输入(GI)：激光功率（GI:1）

2. **激光焊指令**（E3/E4）：
   - 起弧：LASERWELDON [工艺参数文件号] T = 时间参数（s），负值表示提前起弧，0与正值表示滞后起弧
   - 收弧：LASERWELDOFF [工艺参数文件号] T = 时间参数（s）

3. **程序组织**（E6）：按 安全点→接近点→焊接起点(激光开)→焊接终点(激光关)→离开点 的顺序编排，激光开启/关闭与运动指令通过冒号(:)组合在同一行执行。

### Example — laser_welding

在激光焊工作站中，机器人需从安全位置移动到焊接起点并开启激光，沿焊缝运动至终点后关闭激光，最后回到离开位置。程序需按手册规定的顺序组织安全点、接近点、焊接起弧、焊接收弧和离开点。

**Environment and prerequisites:** 前提条件：激光器已连接并通过DI:33（激光器就绪）确认就绪；工艺参数文件号1已配置（含激光功率GO:1、送丝速度GO:2等）；保护气DO:49已开启；点位P[1]~P[5]已在示教器中设定。变量：工艺参数文件号=1，起弧滞后时间T=1.00s，收弧提前时间T=-1.00s，焊接速度V=20，加速度ACC=20。

**Expected result:** 机器人依次执行：以10%速度关节运动到安全点P[1]；以300%速度直线运动到接近点P[2]；以20%速度运动到焊接起点P[3]的同时，滞后1.00s开启激光（工艺文件1）；以20%速度运动到焊接终点P[4]的同时，提前1.00s关闭激光；以300%速度直线运动到离开点P[5]；程序结束。

**Manual:** SX322004《新松机器人激光焊应用操作手册》(C-0) [E3] [E4] [E5] [E6]

```text
NOP
MOVJ P[1] V=10.0 ACC=100 CNT=1
MOVL P[2] V=300.0 ACC=100 CNT=100
MOVJP[3]V=20ACC=20CNT=0:LASERWELDON[1]T =1.00
MOVLP[4]V=20ACC=20CNT=0:LASERWELDOFF[1]T =-1.00
MOVL P[5] VL=300.0 ACC=100 CNT=100
END
```

## [6/17] category_load_analysis

使用负载分析软件时，如何确认工具数模坐标系与机器人法兰坐标系一致，并查看和解释负载分析结果？只需说明操作流程，不要虚构控制指令。

### Retrieved content summary

- 新松机器人负载分析软件使用手册封面，标注为工业机器人技术资料
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V3.0版本/SX322010《新松机器人负载分析软件使用手册》-V1.0/SX322010《新松机器人负载分析软件使用手册》-V1.0.md`, lines 3–13; corpus 4.0, revision V3.0 / V1.0; object `afb0e80538d8af0a37ccd34eef8a290ddea7410d042b615df79b2056bc294f09`.

- 新松机器人负载分析软件使用手册
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V3.0版本/SX322010《新松机器人负载分析软件使用手册》-V1.0/SX322010《新松机器人负载分析软件使用手册》-V1.0.md`, lines 7–9; corpus 4.0, revision V3.0 / V1.0; object `86769aa5445daa91a1b9fff8ab293f4d382dccf931d52a7778402b630217c9ea`.

- 该行为《新松机器人负载分析软件使用手册》中表格的第 7 行，包含 4 个完全为空的单元格，无具体数据或继承值。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V3.0版本/SX322010《新松机器人负载分析软件使用手册》-V1.0/SX322010《新松机器人负载分析软件使用手册》-V1.0.md`, lines 60–65; corpus 5.0, revision V3.0 / V1.0; object `e46bdbec9c8d655b83cda8b1e20e935389ab2c2aef8a332294d2785150fd951c`.

- 新松机器人负载分析软件使用手册（SX322010）文档记录显示，V1.0版本由沙景超于2024年7月31日完成初版。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V3.0版本/SX322010《新松机器人负载分析软件使用手册》-V1.0/SX322010《新松机器人负载分析软件使用手册》-V1.0.md`, lines 30–35; corpus 5.0, revision V3.0 / V1.0; object `7cda9c4c4eeef5bf6c518b4b9408767d045040ba974b2a8ecdca121b15f466b3`.

- 该表格行位于第2行，包含一个单元格，其文本内容为“新松机器人负载分析软件使用手册”，表明该行标识了文档的具体标题或主题。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V3.0版本/SX322010《新松机器人负载分析软件使用手册》-V1.0/SX322010《新松机器人负载分析软件使用手册》-V1.0.md`, lines 7–9; corpus 5.0, revision V3.0 / V1.0; object `fa1885c329e5b2f278cf14e16e9923a574b0a8c67b28e7ccd299f3d3d9caee56`.

- 该行位于《新松机器人负载分析软件使用手册》第6行，包含4个空单元格，无具体数据或继承值。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V3.0版本/SX322010《新松机器人负载分析软件使用手册》-V1.0/SX322010《新松机器人负载分析软件使用手册》-V1.0.md`, lines 54–59; corpus 5.0, revision V3.0 / V1.0; object `c076bb6b70dbd74eff14980e6a2252ccb19f4c96ee60495db82cc4a9a33d8935`.

- 该表格为《新松机器人负载分析软件使用手册》的封面或标题页结构，内容垂直排列，包含新松品牌 Logo 图片、文档主标题“新松机器人负载分析软件使用手册”以及类别标识“工业机器人 技术资料”，用于明确文档所属品牌、具体软件名称及技术领域。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V3.0版本/SX322010《新松机器人负载分析软件使用手册》-V1.0/SX322010《新松机器人负载分析软件使用手册》-V1.0.md`, lines 3–13; corpus 5.0, revision V3.0 / V1.0; object `b4a07d8d09d6a12749ce7d6ae41856f8951533012e93218997381436a683f2ed`.

- 该行位于《新松机器人负载分析软件使用手册》文档的表格中（行索引为6），由4个空单元格组成，无标题或合并单元格继承值，未包含任何具体信息。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V3.0版本/SX322010《新松机器人负载分析软件使用手册》-V1.0/SX322010《新松机器人负载分析软件使用手册》-V1.0.md`, lines 54–59; corpus 4.0, revision V3.0 / V1.0; object `e3aec35c6a751a09e0a208cd12e620c29678b1e2d2c17f8aad95879c077f5a08`.

### Coding or diagnostic answer

The retrieved manual evidence (E1–E8) only contains the title page ('新松机器人负载分析软件使用手册') and the version-history table (V1.0, 2024-07-31, 沙景超, 初版完成). No section describing the operational steps for verifying tool-model coordinate-system alignment with the robot flange coordinate system, nor any procedure for viewing or interpreting load-analysis results, is present in the supplied excerpts. Without documented steps, I cannot construct a faithful contextual example.

## [7/17] category_material_handling

如何配置搬运应用的抓手、工件传感器和电磁阀，并组织抓取工件、确认抓取状态、搬运后释放的作业？

### Retrieved content summary

- 工件传感器指令的功能为检查抓手是否存在工件，并支持选择实时监控或不实时监控模式。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322011《新松机器人搬运应用操作手册》(A-0)/SX322011《新松机器人搬运应用操作手册》(A-0).md`, lines 380–384; corpus 5.0, revision V5.0 / A-0; object `0444d121cec2ecfa4021f2d8112d5c36dc348e3c465719bbcdb8b861476870d6`.

- 工件传感器指令的参数说明：参数1指定有无工件（WithPart/NoPart），参数2指定抓手编号（1-8），参数3指定工件组名称（AllType表示检测所有传感器，TypeNo=名称表示检测特定组，支持注释列表辅助选择），参数4控制实时监控开关（NoMotion/Motion）。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322011《新松机器人搬运应用操作手册》(A-0)/SX322011《新松机器人搬运应用操作手册》(A-0).md`, lines 389–392; corpus 5.0, revision V5.0 / A-0; object `b0ba768d99755d1869575c1bd94fb037c6b2f2a70d4e765d4cf5ca00fd85a5f4`.

- **电磁阀指令**：包含5个参数——参数1控制开关状态（Open/Close/AllOpen/AllClose）；参数2指定抓手编号（1-8）；参数3指定电磁阀阀片组号（1-8，支持点击注释查看名称）；参数4设置检查状态（Check/NoCheck）；参数5控制实时监控开关（NoMotion/Motion）。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322011《新松机器人搬运应用操作手册》(A-0)/SX322011《新松机器人搬运应用操作手册》(A-0).md`, lines 419–422; corpus 5.0, revision V5.0 / A-0; object `ea3a0e80bdb73cdffccef071d884ad55f0db2efe0088fe9ca53db8398e784881`.

- **电磁阀指令** 的说明：该指令包含5个参数：
1. **打开/关闭状态**（参数1）：可选 Open / Close / AllOpen / AllClose；
2. **抓手编号**（参数2）：范围 1-8；
3. **电磁阀阀片组号**（参数3）：范围 1-8，支持点击注释列表查看名称并返回对应编号；
4. **检查状态**（参数4）：可选 Check / NoCheck；
5. **实时监控状态**（参数5）：可选 NoMotion（关闭） / Motion（打开）。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322011《新松机器人搬运应用操作手册》(A-0)/SX322011《新松机器人搬运应用操作手册》(A-0).md`, lines 419–422; corpus 4.0, revision V5.0 / A-0; object `b6236b2bd41d6a76fed4a16bc2a0766b270feefdc54e214d26ad6141361a6265`.

- 第3行为空行，包含4个无内容单元格，源自《新松机器人搬运应用操作手册》。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322011《新松机器人搬运应用操作手册》(A-0)/SX322011《新松机器人搬运应用操作手册》(A-0).md`, lines 40–45; corpus 5.0, revision V5.0 / A-0; object `4da9286c6b4e8a8ac055f595f2d3657da67a9516e83910de9abf6272da4e4502`.

- 工件传感器指令的功能是检查抓手是否存在工件，并支持选择实时监控或不实时监控。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322011《新松机器人搬运应用操作手册》(A-0)/SX322011《新松机器人搬运应用操作手册》(A-0).md`, lines 380–384; corpus 4.0, revision V5.0 / A-0; object `0696ac28069431bf87968485a479eba10c89e9fe32a89efc3bf9d7dd02598831`.

- **工件传感器指令**说明：参数1指定有工件（WithPart）或无工件（NoPart）；参数2为1-8号抓手编号；参数3指定检测所有（AllType）或特定工件组（TypeNo=名称）的传感器，并支持注释列表辅助选择；参数4控制实时监控状态（NoMotion关闭/Motion打开）。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322011《新松机器人搬运应用操作手册》(A-0)/SX322011《新松机器人搬运应用操作手册》(A-0).md`, lines 389–392; corpus 4.0, revision V5.0 / A-0; object `959777195567ea55d1d0ab7297d8241a6259c8186250508411223412b1c2e2c8`.

- 该行为**电磁阀指令**示例，提供了5条 `A03_MH` 抓手控制指令，分别演示了针对特定抓手（GripNo）和气缸号（CylinderNo）的**打开/关闭/全开/全关**操作，并配置了**检测模式**（Check/NoCheck）及**实时监控状态**（Motion/NoMotion）。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322011《新松机器人搬运应用操作手册》(A-0)/SX322011《新松机器人搬运应用操作手册》(A-0).md`, lines 423–426; corpus 5.0, revision V5.0 / A-0; object `f09d8470467539eda6604530ced566cfe986fbc388904990f10eb937a424eba1`.

### Coding or diagnostic answer

在新松机器人搬运应用中，配置抓手、工件传感器和电磁阀的作业流程如下：首先通过电磁阀指令（A03_MH Gripper）控制抓手开合完成抓取或释放；然后通过工件传感器指令（A03_MH PartPresent）检测抓手上是否存在工件以确认抓取状态。典型作业顺序为：关闭抓手抓取工件 → 用工件传感器确认工件存在 → 搬运至目标位置 → 打开抓手释放工件 → 用工件传感器确认工件已脱离。所有指令均支持实时监控（Motion）或关闭实时监控（NoMotion），并可通过 Check/NoCheck 决定是否检测电磁阀状态。

### Example — material_handling

操作员在搬运应用中配置单抓手（GripNo=1）配合电磁阀阀片组1（CylinderNo=1）完成一次完整的抓取-确认-释放作业。机器人先关闭抓手夹紧工件，随后通过工件传感器全信号检测确认工件已牢固抓取，搬运至目标位置后打开抓手释放工件。

**Environment and prerequisites:** 前置条件：新松机器人已安装A03_MH搬运应用模块；抓手编号为1（GripNo=1）；电磁阀阀片组号为1（CylinderNo=1）；工件传感器组使用AllType（检测所有传感器）；实时监控状态为Motion（打开）。用户需根据实际硬件配置替换GripNo、CylinderNo及工件组名称。

**Expected result:** 执行后，抓手电磁阀先关闭完成夹紧，工件传感器返回WithPart确认工件存在，随后电磁阀打开完成释放。若传感器未检测到工件，系统将在Motion实时监控下报警提示抓取失败。

**Manual:** SX322011《新松机器人搬运应用操作手册》(A-0) V5.0 / A-0 [E1] [E3] [E8]

```text
A03_MH Gripper Close GripNo=1 CylinderNo=1 Check Motion ;抓取工件-关闭抓手夹紧
A03_MH PartPresent WithPart GripNo=1 AllType Motion ;确认抓取状态-检测工件存在
A03_MH Gripper Open GripNo=1 CylinderNo=1 Check Motion ;搬运后释放-打开抓手
```

## [8/17] category_offline_interface

使用新松机器人离线接口库时，上位机初始化、建立网络连接、发送运动或下载作业、断开并释放资源的正确调用顺序是什么？请选择一种手册支持的语言举例。

### Retrieved content summary

- 新松机器人离线接口库错误码 -19：接收数据包对象为空，原因是网络异常导致数据丢失。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322009《新松机器人离线接口库操作手册》(C-1)/SX322009《新松机器人离线接口库操作手册》(C-1).md`, lines 16203–16207; corpus 5.0, revision V5.0 / C-1; object `7fd18ba3e6f2ca973a0a59c291c9dcb288abd4672ecf7943edf5f27ff9250ba3`.

- 新松机器人离线接口库使用手册中的表格行展示了三个核心字段：“值”、“状态”和“含义”。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322009《新松机器人离线接口库使用手册》(B-7)/SX322009《新松机器人离线接口库使用手册》(B-7).md`, lines 12160–12164; corpus 4.0, revision V5.0 / B-7; object `c6ede2043ba6aadb8427ef5e191733cb3b5c6bd0601a78e00bfcb29b0df96f85`.

- 该行为新松机器人离线接口库手册中的表格数据行（索引7），包含三列：
1. **序号**：32
2. **模式**：示教模式
3. **第三列**：空值（无内容）

所有单元格均为独立单元格（无合并继承），来自V5.0版本SX322009手册。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322009《新松机器人离线接口库使用手册》(B-7)/SX322009《新松机器人离线接口库使用手册》(B-7).md`, lines 12190–12194; corpus 4.0, revision V5.0 / B-7; object `0d20cd13c863cdfe4b9d08d35c9adcfb22c5f73cf25975ccd7bbbe7a514d1823`.

- 该表格行（索引2）包含单个加粗文本单元格：“新松机器人离线接口库操作手册”，作为标题标识，无其他列或合并单元格关系。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322009《新松机器人离线接口库使用手册》(B-7)/SX322009《新松机器人离线接口库使用手册》(B-7).md`, lines 7–9; corpus 4.0, revision V5.0 / B-7; object `3ff964a18eef632e3c4d6ab8843b784a9164f9a9f6a111abdd23e1e7bf181b8a`.

- 该表为《新松机器人离线接口库使用手册》V5.0 中的**功能接口数据包大小对照表**，列出了各类运动指令及辅助接口的数据长度。主要接口及字节数分布如下：

*   **基础运动指令（P2P/CP 及变体）**：
    *   **69 字节**：Movl_P2P、Movl_CP、Movj_P2P_NOAP、Movj_CP_NOAP 及其 RPY（旋转参数）版本，以及所有 NoEndBack（无回退）变体。
    *   **57 字节**：Movj_P2P、Movj_CP 及其 NoEndBack 变体。
    *   **133 字节**：Movc_P2P、Movc_CP（圆弧运动指令）。
*   **弧线与轨迹控制**：
    *   **83 字节**：ARCL_P、ARCJ_P、SARCL_P、ARCC_P、SARCC_P（各类圆弧插补指令）。
    *   **36 字节**：TRACKON/TRACKOFF 系列（含 ARC、LASER 绝对/相对模式等轨迹跟踪与关闭指令）。
*   **波形与参考信号**：
    *   **19 字节**：WAVEON 系列（SIN、MOON、ANGLE、L、CIRCLE、8 等波形开启指令）及 WAVEON 基础指令。
    *   **11 字节**：WREFP、WAVEREF（波形参考）、WAVEOFF（波形关闭）。
*   **辅助与控制指令**：
    *   **23 字节**：ARCON/ARCOFF 系列（含 UI/UI2 版本）及 PARA_S_UI 系列（参数设置）。
    *   **5 字节**：Delay（延时）、DGO_Out、DGO_Out8。
    *   **4 字节**：DO_Out。
    *   **3 字节**：Send_ShiftOnPOff、AMENDOFF。
    *   **11 字节**：Send_ShiftOnP、AMEDNON。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322009《新松机器人离线接口库使用手册》(B-7)/SX322009《新松机器人离线接口库使用手册》(B-7).md`, lines 3340–3569; corpus 4.0, revision V5.0 / B-7; object `1a5fb8a63f4b355e4d52629d84b53c8b44e786db22bf7e08a675fe03ee564522`.

- 该表格行显示文档标题为“新松机器人离线接口库操作手册”。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322009《新松机器人离线接口库操作手册》(C-1)/SX322009《新松机器人离线接口库操作手册》(C-1).md`, lines 13–15; corpus 5.0, revision V5.0 / C-1; object `ab8c53ec48a6d1077d911a868e4fcb925e58441bfda7e48cf9053bb24ff18537`.

- 该表格详细列出了新松机器人离线接口库的**错误码对照表**，包含三列结构：**错误码**、**错误码定义**及**说明**。内容涵盖了从成功状态（0）到各类异常情况的完整定义：

1.  **成功状态**：错误码 **0** 表示函数调用成功。
2.  **网络与通讯异常**：错误码 **-1, -2, -4, -17, -18, -19, -30** 主要涉及网络断开、超时、数据丢失或校验错误，通常建议检查网线连接、使用 ping 命令诊断网络或检查数据传输完整性。
3.  **参数与数据错误**：错误码 **-3, -5, -20, -38, -39, -41, -44** 涉及参数无效、返回数据无效、数据长度错误、JSON 转换失败或单次发送数据过大等，需检查输入参数范围、数据格式及批量大小。
4.  **初始化与授权问题**：错误码 **-6** 提示需调用 `RobotInit` 或 `ConnectSFtp` 进行初始化；**-22, -45** 涉及授权文件无效、缺失、过期或主板信息不符，需检查 `SiasunRobot.lic` 及系统配置。
5.  **状态与操作限制**：
    *   **-9, -35**：机器人处于报警、运动或作业执行中，禁止当前操作，需清除报警或等待作业完成。
    *   **-11**：作业存储空间已满，需删除部分作业。
    *   **-13, -14, -42**：分别对应执行状态禁止调用、远程控制未启动（需切换权限）及控制器模式错误（示教/执行/远程）。
    *   **-36**：作业名不合法，仅允许字母、数字和下划线。
6.  **版本与系统兼容**：错误码 **-15** 提示离线接口库与机器人程序版本不匹配（机器人版本较低）；**-21, -37, -40** 涉及 SOCKETID 不存在、FTP 或 SFTP 服务错误。
7.  **其他系统错误**：包括日志创建失败（**-34**）、配置文件加载失败（**-25**，需检查 `SysConfig.xml`）及未定义异常（**-43**）。

该表为开发者提供了标准化的错误排查指南，明确区分了网络、参数、状态、授权及系统配置等不同层面的故障原因及处理建议。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322009《新松机器人离线接口库操作手册》(C-1)/SX322009《新松机器人离线接口库操作手册》(C-1).md`, lines 16124–16294; corpus 5.0, revision V5.0 / C-1; object `c35f9e6122335415b390a2f7561ec2885449bcabc4ff840bf3e668a950465f2e`.

- 该表为**新松机器人离线接口库的错误码对照表**，包含三列：`错误码`、`错误码定义` 和 `说明`。共列出 27 个错误条目，涵盖成功状态（0）及各类失败场景（-1 至 -36），主要分类如下：

*   **网络与通信异常**：
    *   发送/接收失败：-1（超时）、-2（断开）、-17/-18/-19（数据包异常/丢失）、-21（Socket ID 无效/断开）。
    *   数据校验/传输错误：-4（校验码错误）、-20（子功能码错误）、-30（数据长度错误）。
*   **配置与初始化问题**：
    *   初始化/加载失败：-6（未初始化/SysConfig.xml缺失）、-16（配置文件打开失败）、-25/-26（系统/指令配置文件加载失败）、-33（转换软件初始化失败）。
    *   授权问题：-22（授权文件无效/过期/主板不符）。
*   **参数与数据格式错误**：
    *   参数无效：-3（参数超范围）、-5（返回数据无效）。
    *   命名/路径规范：-32（路径含空格）、-36（作业名非法，仅限大写字母/数字/下划线）。
*   **机器人状态与业务限制**：
    *   状态冲突：-9（控制器报警需清除）、-13/-35（机器人执行中/运动中，禁止调用/操作）。
    *   资源/功能限制：-11（作业空间已满）、-14（远程功能未启动）、-15（版本不匹配/RC不支持）、-31（作业转换失败）、-34（日志创建失败）。

**建议**：排查时优先检查网络连接（ping/网线）、配置文件完整性（SysConfig.xml, .lic）及参数合法性；若状态冲突，需确认机器人是否处于运动中或存在未清除报警。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322009《新松机器人离线接口库使用手册》(B-7)/SX322009《新松机器人离线接口库使用手册》(B-7).md`, lines 18780–18926; corpus 4.0, revision V5.0 / B-7; object `472cac33730d2b675beaa93c078a6fc199f3961d19af3164c42eba095a85f357`.

### Coding or diagnostic answer

The retrieved evidence (E1, E5, E7, E8) only provides error-code tables, a list of function interface names with byte sizes (e.g., Movl_P2P, Movj_P2P), and brief textual notes such as '在调用接口前，调用RobotInit进行初始化' and '调用SetControlPriorty接口切换控制权限'. No function signatures, parameter types, return types, language-specific API bindings, or code listings are present in any of the evidence items. Without documented function prototypes and a confirmed supported language (C, C++, Python, etc.), it is impossible to construct a valid, evidence-backed code example demonstrating the full init → connect → send-motion/download → disconnect → release sequence.

## [9/17] category_palletizing

如何从开启码垛应用、PLC通讯准备、工具与用户坐标系设置开始，配置产品和码垛工艺，再组织一次码垛作业？

### Retrieved content summary

- 新松机器人码垛应用手册表格第一行，列标题依次为：序号、垛型名称、示例。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322002《新松机器人码垛应用操作手册》(C-1)/SX322002《新松机器人码垛应用操作手册》(C-1).md`, lines 1310–1314; corpus 4.0, revision V5.0 / C-1; object `9e982dec52d916a5e51a5c601db7cd0a81fde7b68a19ea6603b81d2f00dcf4c1`.

- 新松机器人码垛应用操作手册
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322002《新松机器人码垛应用操作手册》(C-1)/SX322002《新松机器人码垛应用操作手册》(C-1).md`, lines 11–13; corpus 5.0, revision V5.0 / C-1; object `0c1e59b7b04ae94ea26bcc5048cd8d974162112a05d0ccef8ef3b064ac2ff6ff`.

- 新松机器人码垛应用操作手册
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322002《新松机器人码垛应用操作手册》(C-1)/SX322002《新松机器人码垛应用操作手册》(C-1).md`, lines 11–13; corpus 4.0, revision V5.0 / C-1; object `ff91c63721415163f70e38155cb975c2cb58c48f8553d5b8f9d15865e1e494c4`.

- 在《新松机器人码垛应用操作手册》的“各作业者可执行作业一览”表中，操作“以操作盘复位报警”仅被赋予权限的角色（对应表中的两个“○”列）可执行，其余角色（对应空白列）无权执行。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322002《新松机器人码垛应用操作手册》(C-1)/SX322002《新松机器人码垛应用操作手册》(C-1).md`, lines 150–155; corpus 4.0, revision V5.0 / C-1; object `35a335344e8067275d36a861e9ff4fdb7ed56c2d7b55d66d77d7101af2a10151`.

- 码垛方式：重叠式（产品横/竖向排列，每层码放方式相同）；示意图：两个并排的3×3网格（左橙右黑线、右蓝），无具体机器人实体或参数。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322002《新松机器人码垛应用操作手册》(C-1)/SX322002《新松机器人码垛应用操作手册》(C-1).md`, lines 1315–1319; corpus 5.0, revision V5.0 / C-1; object `14f3f12cbfef0241c3e99a787b53c3d620e4c86a24dd935e455cc36fd71131a0`.

- 错误代码 30001（码垛工艺生成失败）：原因为码垛工艺生成过程配置出现问题，解决方法是修改码垛工艺相关配置。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322002《新松机器人码垛应用操作手册》(C-1)/SX322002《新松机器人码垛应用操作手册》(C-1).md`, lines 1615–1622; corpus 5.0, revision V5.0 / C-1; object `54eacafec0fdbff1bcda85289adf72aa20315a9e5b802eda02b13dde164e6f4f`.

- 错误 30001（码垛工艺生成失败）：原因为码垛工艺生成过程配置异常，建议修改码垛工艺相关配置。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322002《新松机器人码垛应用操作手册》(C-1)/SX322002《新松机器人码垛应用操作手册》(C-1).md`, lines 1615–1622; corpus 4.0, revision V5.0 / C-1; object `1ada7aac0ddd6afd2ce1c21b562f4838004b4ceb29e9bafd6d5f980ab4736bbe`.

- 码垛模式“纵横交错”（编号4）：同层码放方向相同，相邻层旋转90°；行内含对应示意图。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322002《新松机器人码垛应用操作手册》(C-1)/SX322002《新松机器人码垛应用操作手册》(C-1).md`, lines 1330–1334; corpus 5.0, revision V5.0 / C-1; object `06f4ed88f8c1ed474dc4c51352d03a865c51891e544afbb73efd8baeb7192460`.

### Coding or diagnostic answer

The retrieved evidence from the 新松机器人码垛应用操作手册 (V5.0/C-1) only provides: (1) a table of four pallet pattern types (重叠式, 回字形, 正反交错, 纵横交错) [E1, E5, E8], (2) an operator-permission matrix listing who may perform which actions such as 控制装置电源开/关, 运行模式选择, 示教, 复位报警, 紧急停止 [E4], and (3) a list of palletizing alarm codes 30001–30101 with causes and remedies [E6]. None of these passages contain the step-by-step procedural instructions the question requests: how to open/launch the palletizing application, how to prepare PLC communication, how to set up the tool coordinate system (TCP) and user coordinate system, how to configure product parameters, or how to sequence a complete palletizing job. Because the manual excerpts lack any documented syntax, command sequence, or configuration workflow for these setup steps, a faithful contextual example cannot be constructed from the supplied evidence alone.

## [10/17] category_pneumatic_spot_welding

如何配置气动点焊的设备交互IO、焊接压力和焊点参数，并组织加压、焊接、完成确认及松开焊钳的流程？

### Retrieved content summary

- 该表格列出了气动点焊系统中6项**输出IO**配置参数：序号1至4分别对应“焊接/试验”、“焊接开始”、“焊点号确认”及“报警复位”，各占1个IO点；序号5为4个预留IO；序号6为“焊点编号”，占用32个IO点。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322018《新松机器人气动点焊应用操作手册》-A-0/SX322018《新松机器人气动点焊应用操作手册》-A-0.md`, lines 231–274; corpus 5.0, revision V5.0 / A-0; object `ec309aa64af4ed04af6a6201507cd70658fdec28b45824af17093921d97a877a`.

- 该行记录了一个气动点焊操作配置项：序号2，动作/事件为“焊接开始”，控制方式为“输出IO”，对应的IO点/值为1。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322018《新松机器人气动点焊应用操作手册》-A-0/SX322018《新松机器人气动点焊应用操作手册》-A-0.md`, lines 244–249; corpus 5.0, revision V5.0 / A-0; object `dc5269b7e1fc02d510714e6e63b5007799c48e76c68da393d3bda60ecbf26e87`.

- 该行显示气动点焊（AIRSPOTJ）参数配置：P[1]，VJ=10，ACC=100，CNT=0，DRESS，GUN=1，PRS=1，TWC=0。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322018《新松机器人气动点焊应用操作手册》-A-0/SX322018《新松机器人气动点焊应用操作手册》-A-0.md`, lines 882–884; corpus 5.0, revision V5.0 / A-0; object `f0cd1328e56049f39c88c9cd9f14d42cf4af5326f20c0fbc5f3a5ad2ec26ba7e`.

- OP6：切换气动点焊工艺模式（工艺开/正常、工艺关-仿真、工艺关-干运行）以进行试运行或仿真测试；详见第5章气动点焊快捷键。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322018《新松机器人气动点焊应用操作手册》-A-0/SX322018《新松机器人气动点焊应用操作手册》-A-0.md`, lines 340–343; corpus 5.0, revision V5.0 / A-0; object `58b77b4932b8ffa322e9f4754681c001a6348aa76656ed21812986d92e375618`.

- OP6：切换气动点焊工艺模式（工艺开/正常、工艺关-仿真、工艺关-干运行）以进行试运行或仿真测试，详见手册第5章“气动点焊快捷键”。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322018《新松机器人气动点焊应用操作手册》-A-0/SX322018《新松机器人气动点焊应用操作手册》-A-0.md`, lines 340–343; corpus 4.0, revision V5.0 / A-0; object `169d5d5f7d827c7829cfb201bd51483b137632942c72163e9e7c5e3f4ffe5360`.

- 新松机器人气动点焊参数行：程序 AIRSPOTJ，点 P[1]；VJ=10、ACC=100、CNT=0；WELD 枪号 1、PRS=1；程序号 PROGNo=123456789；GLF=1。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322018《新松机器人气动点焊应用操作手册》-A-0/SX322018《新松机器人气动点焊应用操作手册》-A-0.md`, lines 837–839; corpus 4.0, revision V5.0 / A-0; object `7385c27aeaedb851fa5fcf29d2547a97ec638535af0e371f1bd3defdfdb9bc48`.

- 该表详细描述了气动点焊指令 `AIRSPOTJ P[1]` 的配置，其核心功能是**在修磨位置执行焊钳闭合与加压**。指令参数包括运行速度 (VJ=10)、加速度 (ACC=100)、计数 (CNT=0)、枪号 (GUN=1) 及压力号 (PRS=1) 等。

表格下方的“说明”部分列出了该指令涉及的 7 个关键参数项及其含义：
1. **位置变量号**
2. **运行速度**
3. **加速度**
4. **逼近等级**
5. **焊钳特性编号**（须与当前焊钳号一致）
6. **焊接压力文件号**（取值范围 1-32）
7. **修磨方式号**（0=仅加压不计次；1=加压且记录修磨次数）
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322018《新松机器人气动点焊应用操作手册》-A-0/SX322018《新松机器人气动点焊应用操作手册》-A-0.md`, lines 881–918; corpus 5.0, revision V5.0 / A-0; object `300239c9381ac29feb6d25dddefa2ef0bce827f5ff67efad2e06fc0898e03c53`.

- 该表格定义了**气动点焊机器人控制指令 `AIRSPOTJ`** 的结构与参数含义：

1.  **指令行**（跨3列）：展示了一个完整的命令示例，包含位置点、速度、加速度、焊枪号、压力档位、程序号及全局标志等关键执行参数。
2.  **功能**：描述机器人携带焊钳通过关节运动，按指定行程、压力及条件执行焊接任务。
3.  **参数说明**（左侧合并单元格“说明”，右侧分8行详细定义）：
    *   **参数1**：位置变量号
    *   **参数2**：运行速度
    *   **参数3**：加速度
    *   **参数4**：逼近等级（0或1）
    *   **参数6**：焊钳特性编号（需与当前焊钳一致）
    *   **参数7**：焊接压力文件号（1-32）
    *   **参数8**：焊机通讯焊接文件号
    *   **参数9**：间隙参数（1-4），定义焊钳焊接前后的开合状态组合（如小开/大开及回程位置）

注：表格中参数编号跳过了“参数项 5”，直接列举了1-4及6-9项。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322018《新松机器人气动点焊应用操作手册》-A-0/SX322018《新松机器人气动点焊应用操作手册》-A-0.md`, lines 836–877; corpus 5.0, revision V5.0 / A-0; object `884747df248383b277f1d187ffc6ed9fa23942b5545fcdfeeec559a097303602`.

### Coding or diagnostic answer

根据手册E7和E8，气动点焊通过AIRSPOTJ指令实现加压(DRESS)和焊接(WELD)流程。E1列出了设备交互输出IO（焊接/试验、焊接开始、焊点号确认、报警复位、焊点编号）。焊接压力通过PRS参数（1-32号压力文件）指定，焊点参数通过PROGNo（焊机通讯焊接文件号）和GLF（间隙参数，控制焊钳焊接前后行程）配置。流程为：DRESS加压→WELD焊接→焊点号确认IO→GLF参数控制焊钳松开位置。

### Example — pneumatic_spot_welding

在车身侧围焊接工位，机器人携带1号焊钳对指定焊点执行气动点焊：先加压闭合焊钳，再以指定压力和焊接条件执行焊接，完成后确认焊点编号，焊钳按间隙参数回到小开位置。

**Environment and prerequisites:** 位置变量P[1]已示教至焊点位置；焊钳特性编号GUN=1；焊接压力文件号PRS=1（1~32）；焊机通讯焊接文件号PROGNo=123456789；间隙参数GLF=3（大开-小开，焊接前大开，焊接后回到小开）；运行速度VJ=10；加速度ACC=100；逼近等级CNT=0；修磨方式TWC=0（只加压不计修磨次数）。

**Expected result:** 机器人以速度10、加速度100运动至P[1]位置，焊钳闭合加压（DRESS），随后以压力文件1和焊接文件123456789执行焊接（WELD），焊接完成后输出焊点号确认IO，焊钳从大开位置松开回到小开位置（GLF=3）。

**Manual:** SX322018《新松机器人气动点焊应用操作手册》-A-0, V5.0 / A-0 [E1] [E7] [E8]

```text
AIRSPOTJ P[1] VJ=10 ACC=100 CNT=0 DRESS GUN=1 PRS=1 TWC=0;
AIRSPOTJ P[1] VJ=10 ACC=100 CNT=0 WELD GUN=1 PRS=1 PROGNo=123456789 GLF=3;
SETIO 焊点号确认=1;
```

## [11/17] category_spot_welding

伺服点焊作业前如何完成焊钳轴校零、压力标定和焊点参数配置，并组织一次加压、焊接及打开焊钳的流程？

### Retrieved content summary

- 点焊程序参数：程序号P[1]，点焊速度VJ=10，加速度ACC=100，计数CNT=0，焊枪GUN=1，压力PRS=1，程序编号PROGNo=123456789，GLF=1。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322007《新松机器人点焊应用操作手册》（A-2）/SX322007《新松机器人点焊应用操作手册》（A-2）.md`, lines 1016–1018; corpus 4.0, revision V5.0 / A-2; object `f16eb502d084995168143d55db76d2ede24058b487ee23e8963392a2a05c8038`.

- 该行描述了点焊参数设置：点焊指令为 SPOTJ，脉冲号为 P[1]，具体参数包括振动电压（VJ）为 10，准确度（ACC）为 100，计数（CNT）为 0，工装类型为 DRESS，枪号（GUN）为 1，压力状态（PRS）为 1，扭转控制（TWC）为 0。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322007《新松机器人点焊应用操作手册》（A-2）/SX322007《新松机器人点焊应用操作手册》（A-2）.md`, lines 1106–1108; corpus 5.0, revision V5.0 / A-2; object `4800886245116e4511c2d37c9ba1d6f439246456affc3bd840acd6f2b5c0b78f`.

- 第2行数据显示：在“无电池”状态下，执行“1校零”操作，其具体条件为换枪时焊钳闭合且取枪时进行校零。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322007《新松机器人点焊应用操作手册》（A-2）/SX322007《新松机器人点焊应用操作手册》（A-2）.md`, lines 659–664; corpus 4.0, revision V5.0 / A-2; object `6afc34643ba49787ef39362785bfa88ce9ba021542568de0e2e0cb2999cd04ef`.

- **A/1** | 2025年6月13日 | 盖梓涵 | 修改点焊快捷键、IO/焊钳/修磨压力/开关配置描述及参数；新增多修磨器、后台修磨功能说明；更新第3章点焊指令表格
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322007《新松机器人点焊应用操作手册》（A-2）/SX322007《新松机器人点焊应用操作手册》（A-2）.md`, lines 2461–2466; corpus 5.0, revision V5.0 / A-2; object `63b141d4be6856a27781bb04087023c4332f4d586f756a4c2e8040272746fac9`.

- 初始化指令说明：`<参数1>` 为焊点个数，取值范围为 0-100。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322007《新松机器人点焊应用操作手册》（A-2）/SX322007《新松机器人点焊应用操作手册》（A-2）.md`, lines 1539–1542; corpus 5.0, revision V5.0 / A-2; object `140472560accd67d0cb8841ac8a188129a1e449b8ceaf48d4d746d78408a2aa9`.

- 功能：焊钳闭合与加压，并计算电极磨损量。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322007《新松机器人点焊应用操作手册》（A-2）/SX322007《新松机器人点焊应用操作手册》（A-2）.md`, lines 1109–1112; corpus 4.0, revision V5.0 / A-2; object `06c2b5f3d996e698a5173116c524d4fd3aa4641d937d650856559fda986a10c9`.

- 说明：参数项 1 为焊钳编号。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322007《新松机器人点焊应用操作手册》（A-2）/SX322007《新松机器人点焊应用操作手册》（A-2）.md`, lines 1216–1220; corpus 5.0, revision V5.0 / A-2; object `f33896ea522272de2e1fc1689f4614a6a3988b523b08dfb5a23f02e45c7ea908`.

- 该行为一条横跨3列的点焊参数配置指令，内容为：“SPOTJ P[1] VJ=10 ACC=100 CNT=0 WELD GUN=1 PRS=1 PROGNo=123456789 GLF=1；”，具体参数包括：程序位置P[1]、速度VJ=10、加速度ACC=100、计数CNT=0、焊枪GUN=1、压力PRS=1、程序号PROGNo=123456789、GLF=1。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322007《新松机器人点焊应用操作手册》（A-2）/SX322007《新松机器人点焊应用操作手册》（A-2）.md`, lines 1016–1018; corpus 5.0, revision V5.0 / A-2; object `c249a7203edf4f5de46863e7552239450436ed16f49388ee2ab4e6e2e0ebcbaa`.

### Coding or diagnostic answer

在伺服点焊作业前，需完成三项准备工作：(1) 焊钳轴校零——根据E3，校零是换枪时的配置选项（类型1为

### Example — spot_welding

操作员在伺服点焊工作站上，针对1号焊钳执行一次完整的点焊循环：先初始化焊点计数，再执行焊接指令（含压力文件号、焊接程序号、间隙文件号），最后放枪打开焊钳。

**Environment and prerequisites:** 前提：机器人已上电、焊钳已安装并选择校零类型（E3中类型1：焊钳闭合时校零）；压力文件号PRS=1已在焊接压力配置（E4，A/2新增2.6节）中设定；焊点参数通过SWInit初始化。变量：P[1]为焊点位置变量，VJ=10为运行速度，ACC=100为加速度，CNT=0为逼近等级，GUN=1为焊钳编号，PROGNo=123456789为焊机通讯焊接文件号，GLF=1为间隙文件号。

**Expected result:** SWInit将焊点计数初始化为10个；SPOTJ WELD指令驱动焊钳按P[1]位置执行焊接动作，调用PRS=1压力文件和PROGNo=123456789焊接程序，焊接前后执行GLF=1间隙运动；GUNPLACE将1号焊钳放回指定位置，完成打开焊钳动作。

**Manual:** SX322007《新松机器人点焊应用操作手册》（A-2） [E1] [E5] [E7] [E2] [E3] [E4]

```text
A04_SW SWInit Count=10；
SPOTJ P[1] VJ=10 ACC=100 CNT=0 WELD GUN=1 PRS=1 PROGNo=123456789 GLF=1；
GUNPLACE GUN #1
```

## [12/17] category_spr_riveting

如何配置SPR铆机的工作模式、IO及通讯，并按基本作业流程完成一次铆接和防漏铆确认？

### Retrieved content summary

- SPR防漏铆检测指令：无说明。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322014《新松机器人SPR铆接应用操作手册》(A-1)/SX322014《新松机器人SPR铆接应用操作手册》(A-1).md`, lines 356–359; corpus 4.0, revision V5.0 / A-1; object `ee1642c6b58da1f5203a3e150847b18d535a72f93f66eda320f86f1bde183100`.

- 该指令配置机器人运动至SPR铆接位置P1（速度200，加速度100），由2号铆枪执行铆接作业，并关联程序号102及下一程序号103。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322014《新松机器人SPR铆接应用操作手册》(A-1)/SX322014《新松机器人SPR铆接应用操作手册》(A-1).md`, lines 1489–1492; corpus 4.0, revision V5.0 / A-1; object `e1e29f24572b38205573b4e3dbc043f4720fd9add2d55d0175a7033529ed3b3a`.

- SPR初始化指令说明：参数1为铆枪号（写入用户整型变量436），参数2为控制器号（写入变量437），参数3为防漏铆检测铆点数量（写入变量438）。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322014《新松机器人SPR铆接应用操作手册》(A-1)/SX322014《新松机器人SPR铆接应用操作手册》(A-1).md`, lines 300–303; corpus 5.0, revision V5.0 / A-1; object `7f3f1f5d760b1c171597891a8f00b209b2a3d38f67f6a20270b74ec874a00942`.

- SPR铆接指令：功能为运动到铆接点，进行SPR铆接
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322014《新松机器人SPR铆接应用操作手册》(A-1)/SX322014《新松机器人SPR铆接应用操作手册》(A-1).md`, lines 252–256; corpus 4.0, revision V5.0 / A-1; object `b40149430ab475d5f7795a4593dcc6256d8ed9464fbd386fd62c469056336424`.

- 在“SPR防漏铆检测指令”项下，该行对应说明为“无”。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322014《新松机器人SPR铆接应用操作手册》(A-1)/SX322014《新松机器人SPR铆接应用操作手册》(A-1).md`, lines 356–359; corpus 5.0, revision V5.0 / A-1; object `bd08c8416a4d3c36983fed463ee103717dcfcab978e74112b12e81485464423a`.

- SPRL P2 VL=200 ACC=100 CNT=0 ET=1 GUN=2 RCNo=1 PROGNo=103 NEXTPROGNo=104 GUNOPEN=40; 运动到SPR铆接位置P2，铆枪2进行铆接。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322014《新松机器人SPR铆接应用操作手册》(A-1)/SX322014《新松机器人SPR铆接应用操作手册》(A-1).md`, lines 1497–1500; corpus 4.0, revision V5.0 / A-1; object `30b88bf66a7f5c08d35e9e08c91966ed37f56530860ec9b65dc03f76f80b10d4`.

- SPR铆接指令示例：依次执行SPRJ（关节速度，如VJ=10，含INTERLOCK）和SPRL（直线速度，如VL=200，含ET）指令，分别运动至P1至P4点进行铆接；各步均配置ACC=100、CNT=0、GUN=1、RCNo=1，并通过PROGNo/NEXTPROGNo串联程序号（100→104），GUNOPEN值随点位置变化（20或40）。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322014《新松机器人SPR铆接应用操作手册》(A-1)/SX322014《新松机器人SPR铆接应用操作手册》(A-1).md`, lines 265–268; corpus 4.0, revision V5.0 / A-1; object `5da1b58837d326f4117e2d6981ab79c749d5a2f8dc0258972b67097ddf2b1f7f`.

- SPR防漏铆检测指令的功能是校验实际铆点数与初始化设定值的一致性，若两者不符则触发机器人暂停并报警。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322014《新松机器人SPR铆接应用操作手册》(A-1)/SX322014《新松机器人SPR铆接应用操作手册》(A-1).md`, lines 347–351; corpus 4.0, revision V5.0 / A-1; object `945bf1633954cdd7d94a4e764287ea78dc904f387ea33062a206d8f9de78c949`.

### Coding or diagnostic answer

根据《新松机器人SPR铆接应用操作手册》(A-1) V5.0/A-1，SPR铆接的基本作业流程为：(1) 使用 A13_SPR Init 指令初始化铆枪，设置铆枪号(Gun)、控制器号(RCNo)和防漏铆检测数量(Count)，这完成了铆枪IO及通讯参数的配置；(2) 使用 SPRL（直线）或 SPRJ（关节）指令运动到铆接位置并执行铆接，其中 GUN 指定铆枪号、RCNo 指定控制器号、PROGNo/NEXTPROGNo 为铆钉ID、GUNOPEN 为开口位置；(3) 所有铆接完成后，使用 A13_SPR ProcessCheck 指令进行防漏铆检测，系统会校验实际铆点数是否与初始化时设置的 Count 一致，不一致则机器人暂停并报警。

### Example — spr_riveting

操作员需为铆枪1配置SPR铆接参数（控制器1，预期铆接2个铆点），依次在P1和P2位置完成铆接，最后执行防漏铆检测确认无漏铆。

**Environment and prerequisites:** 前提条件：SPR铆枪1已连接至控制器1；位置变量P1、P2已在示教器中定义；机器人处于自动模式且安全门关闭。变量：Gun=1（铆枪号），RCNo=1（控制器号），Count=2（防漏铆检测铆点数量），VL=200 mm/s（直线速度），ACC=100%（加速度），ET=1（外部工具号），PROGNo=100/101（铆钉ID），GUNOPEN=40（开口位置）。

**Expected result:** 机器人先初始化铆枪1并记录预期铆点数为2；随后以200 mm/s直线速度运动到P1完成第一次铆接，再运动到P2完成第二次铆接；最后执行防漏铆检测，系统校验实际铆点数(2)与初始化设定(2)一致，检测通过，流程正常结束。若漏铆则机器人暂停并报警。

**Manual:** SX322014《新松机器人SPR铆接应用操作手册》(A-1) V5.0 / A-1 [E3] [E4] [E1] [E2] [E8]

```text
A13_SPR Init Gun=1 RCNo=1 Count=2 ;初始化铆枪1，防漏铆检测数量为2
SPRL P1 VL=200 ACC=100 CNT=0 ET=1 GUN=1 RCNo=1 PROGNo=100 NEXTPROGNo=101 GUNOPEN=40 ;运动到P1进行铆接
A13_SPR ProcessCheck ;防漏铆检测
```

## [13/17] category_stud_welding

如何配置螺柱焊焊机的工作参数、IO及通讯，并按基本作业流程完成一次焊接及防漏焊确认？

### Retrieved content summary

- 螺柱焊初始化指令参数说明：参数1为焊枪号（变量号511），参数2为防漏焊检测焊点数量（变量号512）。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322013《新松机器人螺柱焊应用操作手册》(A-2)/SX322013《新松机器人螺柱焊应用操作手册》(A-2).md`, lines 292–295; corpus 4.0, revision V5.0 / A-2; object `bf5764a9c4ede0d3d14e014609f63e46d24ed72a581945755d080b8f31b4ee28`.

- 螺柱焊初始化指令的参数说明：参数1为焊枪号（变量号511），参数2为防漏焊检测的焊点数量（变量号512）。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322013《新松机器人螺柱焊应用操作手册》(A-2)/SX322013《新松机器人螺柱焊应用操作手册》(A-2).md`, lines 292–295; corpus 5.0, revision V5.0 / A-2; object `d737dcc7c2dd570cc4cba44d59fb030c0e9f4cfc275207f02e44f5e7285f4867`.

- 螺柱焊防漏焊检测指令的说明为：无。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322013《新松机器人螺柱焊应用操作手册》(A-2)/SX322013《新松机器人螺柱焊应用操作手册》(A-2).md`, lines 348–351; corpus 5.0, revision V5.0 / A-2; object `9e09c016b1c51a1f78929e76ca0ac9b955ff62103c541496a1f3f74297951c74`.

- 该行为“螺柱焊焊接指令”的参数说明，定义了8个参数：参数1为位置变量序号；参数2为执行速度（VL直线速度mm/s或VJ关节速度1-100%）；参数3为加速度（1-120%，120%为最大）；参数4为逼近等级（0不连续/1连续）；参数5为外部工具号（1-3）；参数6为干涉区文件号；参数7为焊枪号（1-5，变量号511）；参数8为程序号（1-4096，变量号512）。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322013《新松机器人螺柱焊应用操作手册》(A-2)/SX322013《新松机器人螺柱焊应用操作手册》(A-2).md`, lines 257–260; corpus 5.0, revision V5.0 / A-2; object `a31cc444101c2d97ee4236aa870c1c0b08d81ad38624ca5d7ea822522dd216d9`.

- 螺柱焊指令：移动至焊接位置P5，由焊枪2执行焊接（参数：VJ=20, ACC=100, CNT=0, INTERLOCK=1, PROGNo=3）。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322013《新松机器人螺柱焊应用操作手册》(A-2)/SX322013《新松机器人螺柱焊应用操作手册》(A-2).md`, lines 573–576; corpus 5.0, revision V5.0 / A-2; object `f7a6514d4fd02078786f4d642c4d441b58c371f954d6da8fa69bd67cf8dd338f`.

- 螺柱焊初始化指令功能：螺柱焊焊枪初始化，设置防漏焊检测数量。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322013《新松机器人螺柱焊应用操作手册》(A-2)/SX322013《新松机器人螺柱焊应用操作手册》(A-2).md`, lines 283–287; corpus 5.0, revision V5.0 / A-2; object `32b2f6a205e10d49500396d323bf2df87d44e8903ad2f7d0a69736aeb4a6484f`.

- 螺柱焊防漏焊检测指令示例：`A20_STUD ProcessCheck ;注释内容//防漏焊检测。`
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322013《新松机器人螺柱焊应用操作手册》(A-2)/SX322013《新松机器人螺柱焊应用操作手册》(A-2).md`, lines 352–355; corpus 4.0, revision V5.0 / A-2; object `5a7b118fbe2909cd680287efbd876359d90f2e8d83d74ab4c415206a59686bb4`.

- 螺柱焊焊接指令说明：该指令包含8个参数：1.位置变量序号（可注释）；2.执行速度（直线速度VL/mm/s 或 关节速度VJ/1-100%）；3.加速度（1-120%，120%为最大）；4.逼近等级（0不连续/1连续）；5.外部工具号（1-3）；6.干涉区文件号；7.焊枪号（1-5，变量号511）；8.程序号（1-4096，变量号512）。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322013《新松机器人螺柱焊应用操作手册》(A-2)/SX322013《新松机器人螺柱焊应用操作手册》(A-2).md`, lines 257–260; corpus 4.0, revision V5.0 / A-2; object `ca785caef7889e3991c2b59a304cac752b060910ddeb14a5fa02b783a4730caa`.

### Coding or diagnostic answer

根据《新松机器人螺柱焊应用操作手册》(A-2) V5.0/A-2，螺柱焊基本作业流程为：(1) 使用 A20_STUD Init 指令初始化焊枪号(GUN)和防漏焊检测焊点数量(Count)；(2) 使用 MOVL 运动到安全位置；(3) 使用 STUDJ/STUDL 指令以指定速度(VJ/VL)、加速度(ACC)、逼近等级(CNT)、干涉区(INTERLOCK)、焊枪号(GUN)和程序号(PROGNo)执行焊接；(4) 焊接完成后使用 A20_STUD ProcessCheck 指令进行防漏焊检测，若实际焊点数与初始化设置不一致则机器人暂停并报警。注意：所提供的证据中未包含IO配置和通讯配置的具体指令或参数说明，本示例仅覆盖工作参数配置、焊接执行及防漏焊确认流程。

### Example — stud_welding

操作员需为A20_STUD螺柱焊应用配置焊枪2，设定防漏焊检测数量为3个焊点，依次对P1、P2、P3三个位置执行关节速度焊接，最后进行防漏焊确认。

**Environment and prerequisites:** 机器人型号：A20_STUD螺柱焊应用；焊枪号：2（变量号511）；防漏焊检测数量：3（变量号512）；焊接位置：P1、P2、P3；关节速度：VJ=20%；加速度：ACC=100%；逼近等级：CNT=0（不连续）；干涉区文件号：1；程序号：3（变量号512）；安全移动速度：VL=20 mm/s。

**Expected result:** 机器人依次完成P1、P2、P3三个焊点的螺柱焊接，每次焊接前运动到安全位置。ProcessCheck指令校验实际焊接点数为3，与初始化设置一致，流程正常结束；若实际焊点数不等于3，机器人将暂停并触发报警。

**Manual:** SX322013《新松机器人螺柱焊应用操作手册》(A-2) V5.0/A-2 [E1] [E3] [E4] [E5]

```text
A20_STUD Init Gun=2 Count=3
MOVL VL=20
STUDJ P1 VJ=20 ACC=100 CNT=0 INTERLOCK=1 GUN=2 PROGNo=3
MOVL VL=20
STUDJ P2 VJ=20 ACC=100 CNT=0 INTERLOCK=1 GUN=2 PROGNo=3
MOVL VL=20
STUDJ P3 VJ=20 ACC=100 CNT=0 INTERLOCK=1 GUN=2 PROGNo=3
MOVL VL=20
A20_STUD ProcessCheck
END
```

## [14/17] category_teaching_free_welding

免示教焊接软件如何配置机器人与视觉设备、创建工件、设置扫描区域和焊缝规则，再规划并执行焊接任务？请区分服务端配置和客户端操作。

### Retrieved content summary

- 新松机器人免示教焊接软件操作手册（工业机器人技术资料）
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V3.0版本/SX322008《新松机器人免示教焊接软件操作手册》-V1.0/SX322008《新松机器人免示教焊接软件操作手册》-V1.0.md`, lines 3–13; corpus 5.0, revision V3.0 / V1.0; object `24ccad338a9ea275f1f3b5ee5b50b729d32842d27a1ecd326876fdb55bc2d00f`.

- 新松机器人免示教焊接软件操作手册（工业机器人技术资料）
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V3.0版本/SX322008《新松机器人免示教焊接软件操作手册》-V1.0/SX322008《新松机器人免示教焊接软件操作手册》-V1.0.md`, lines 3–13; corpus 4.0, revision V3.0 / V1.0; object `f32c34c69d02e8df3c4819bebaecc01f1d59a807687f072389c335026c26f2ea`.

- 新松机器人免示教焊接软件操作手册
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V3.0版本/SX322008《新松机器人免示教焊接软件操作手册》-V1.0/SX322008《新松机器人免示教焊接软件操作手册》-V1.0.md`, lines 7–9; corpus 4.0, revision V3.0 / V1.0; object `dfe3159a01c20e8b9a0100230992d237eef0804bc8c369ec1fe86cf509fd167a`.

- 该行位于《新松机器人免示教焊接软件操作手册》中，包含4个非标题列，所有单元格内容均为空，无跨行或跨列合并，且未继承任何值。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V3.0版本/SX322008《新松机器人免示教焊接软件操作手册》-V1.0/SX322008《新松机器人免示教焊接软件操作手册》-V1.0.md`, lines 48–53; corpus 4.0, revision V3.0 / V1.0; object `4f9395395fef8584d54eb4c9724453c040db12d8130c2be982e9a3a1262c8427`.

- 用户配置：展示用户配置界面示意图，说明需在此配置示教、原点、外部设备通讯、干涉区、中断操作等各项条件。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322001《新松机器人通用操作手册》(C-1)/SX322001《新松机器人通用操作手册》(C-1).md`, lines 1228–1231; corpus 5.0, revision V5.0 / C-1; object `4f0b7e3f578640e7c5b1b6da88e99342ef771abbb6383c49468b4ce930e3fb60`.

- 该表格定义了一个机器人焊接作业的指令序列，包含“作业指令”与“说明”两列。流程从 **NOP** 开始，依次执行：
1.  **定位与起弧**：移动至安全点 P[1]，接着移动到焊缝起点 P[2]，然后执行 **ARCON[1][1]** 起弧。
2.  **焊接过程**：执行 **LTWLT** 渐变指令（参数 A_DIS/B_DIS=20, A_ANGLE/B_ANGLE=±10，需插入运动指令间）进行焊接，随后移动至焊缝终点 P[3]。
3.  **收尾**：执行 **ARCOFF[1]** 熄弧，移动至结束安全点 P[4]，最后以 **END** 指令结束程序。

所有运动指令（MOVL）均设置速度 V=100、加速度 ACC=20、计数 CNT=0。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322003《新松机器人弧焊应用操作手册》(C-1)/SX322003《新松机器人弧焊应用操作手册》(C-1).md`, lines 3148–3189; corpus 5.0, revision V5.0 / C-1; object `7ea88ad744723ea35bacd4366420bc7cc6087ea06d4b12ecfc66199fa6d2a04e`.

- 该表格定义了一个基于激光视觉传感的机器人弧焊程序序列，包含两列：“作业”（指令）与“说明”。程序流程如下：

1.  **初始化**：设置激光传感器设备号（`LSENSOR NO=1`）和任务号（`LSENSOR JOB=31`）。
2.  **激光检测与补偿**：
    *   移动至起点检测位置 `P[1]`。
    *   执行激光搜索（`SEARCH LSENSOR`），结合可选偏移 `PR[98]` 计算补偿，将焊接起点坐标存入 `P[3]`。
    *   移动至终点检测位置 `P[4]`。
    *   执行激光搜索，结合可选偏移 `PR[99]` 计算补偿，将焊接终点坐标存入 `P[6]`。
3.  **焊接执行**：
    *   移动至安全点 `P[7]`，再移至激光校正后的焊接起点 `P[3]`。
    *   调用文件 `#1`（起弧）和文件 `#2`（焊接参数）开始焊接（`ARCON`）。
    *   移动至激光校正后的焊接终点 `P[6]`。
    *   调用文件 `#1` 收弧（`ARCOFF`）。
4.  **收尾**：移动至最终安全点 `P[8]`，程序结束（`END`）。

**核心逻辑**：通过激光传感动态识别焊缝首尾位置，应用预存补偿量修正坐标，实现高精度的自动对位焊接。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322003《新松机器人弧焊应用操作手册》(C-1)/SX322003《新松机器人弧焊应用操作手册》(C-1).md`, lines 5466–5527; corpus 5.0, revision V5.0 / C-1; object `f027a42addeb4cbaa00c0681fdbc57b5b6cfde53340167201952a5ab4ebf27c6`.

- 该行首列及末列为空；中间列继承自上一行，内容分别为“和焊机ID一致”、“默认0即可”以及“根据情况设置（如设置2，机器人端从17位IO开始）”。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322003《新松机器人弧焊应用操作手册》(B-5)/SX322003《新松机器人弧焊应用操作手册》(B-5).md`, lines 1093–1096; corpus 4.0, revision V5.0 / B-5; object `6a9eb53de993d39ae8df660d5701e41570a0f6d649e107364351869e00472496`.

### Coding or diagnostic answer

The retrieved evidence for the teaching-free welding software manual (E1–E4) contains only the cover page (title, logo) and the version-revision history table (V1.0, 2024-06-03, 沙景超, 初版完成). No operational content is present: there are no instructions for configuring the robot or vision device, creating workpieces, defining scan areas, setting weld-seam rules, planning or executing welding tasks, and no distinction between server-side and client-side operations. The other evidence (E5–E8) belongs to the general operation manual and the arc-welding application manual, which cover teach-pendant UI icons, standard welding program instructions (MOVL/ARCON/ARCOFF/LTWLT), laser-search SEARCH syntax, and welder bus-IO mapping—none of which describe the teaching-free (免示教) software workflow. Because the specific syntax, menu paths, configuration fields, and server/client role separation for the 免示教焊接软件 are absent from all supplied evidence, a supported contextual example cannot be constructed.

## [15/17] category_tool_quick_change

如何配置快换停靠站、快换盘和IO，并组织放下当前工具、确认解锁、拾取目标工具和确认锁紧的基本作业流程？

### Retrieved content summary

- 快换工具锁紧、解锁指令：格式为 `A02_TC Docking Unlock/Lock ToolNo= [注释]`
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322015《新松机器人快换应用操作手册》(A-0)/SX322015《新松机器人快换应用操作手册》(A-0).md`, lines 294–297; corpus 5.0, revision V5.0 / A-0; object `d112e186cf20aebf3b508fd1f3f861edabeb1dcde37ae72fb70ced4ae1265415`.

- 快换工具锁紧、解锁指令 - 功能：工具解锁指令
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322015《新松机器人快换应用操作手册》(A-0)/SX322015《新松机器人快换应用操作手册》(A-0).md`, lines 289–293; corpus 5.0, revision V5.0 / A-0; object `7ffb1dbeb9fb0ef4b2c66a7236fa74c8ff08a919044d7ba41d6835c01c876c41`.

- 快换工具锁紧、解锁指令示例：`A02_TC Docking Unlock ToolNo=1` 用于解锁工具1。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322015《新松机器人快换应用操作手册》(A-0)/SX322015《新松机器人快换应用操作手册》(A-0).md`, lines 302–305; corpus 4.0, revision V5.0 / A-0; object `ac6d902c784fed29060fb4d86044c2be372a5f2239521c1db6720486d0a1e46a`.

- “快换工具锁紧、解锁指令”行的“格式”为：A02_TC Docking Unlock/Lock ToolNo= 注释。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322015《新松机器人快换应用操作手册》(A-0)/SX322015《新松机器人快换应用操作手册》(A-0).md`, lines 294–297; corpus 4.0, revision V5.0 / A-0; object `cb6869497fae3a682eb3ce16318e01c8568a8ff4804a210242bdeff18149c9d5`.

- 快换工具锁紧、解锁指令举例：A02_TC Docking Unlock ToolNo=1（解锁）
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322015《新松机器人快换应用操作手册》(A-0)/SX322015《新松机器人快换应用操作手册》(A-0).md`, lines 302–305; corpus 5.0, revision V5.0 / A-0; object `33a4aa4eb400591b4f7b5d3102c7b6d354e65f9182af9d9a43aa525070309fa1`.

- 快换工具锁紧/解锁指令的参数说明：参数1定义功能，参数2指定锁紧或解锁操作，参数3指定工具编号（范围1-16）。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322015《新松机器人快换应用操作手册》(A-0)/SX322015《新松机器人快换应用操作手册》(A-0).md`, lines 298–301; corpus 4.0, revision V5.0 / A-0; object `f7ea0e90f30d0c47088416b290fbcb813e42607c42ccbc72d623c3c26b0c7967`.

- 该行列出了“快换工具锁紧、解锁指令”功能类别下的“工具解锁指令”。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322015《新松机器人快换应用操作手册》(A-0)/SX322015《新松机器人快换应用操作手册》(A-0).md`, lines 289–293; corpus 4.0, revision V5.0 / A-0; object `456a8be9fc6a5d10af4754191dfe9989e4162ac7e8697a866abc61041dccf551`.

- 工具切换指令示例：执行 `A02_TC ChangeTool ToolNo=1` 指令可切换至对应工具1。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322015《新松机器人快换应用操作手册》(A-0)/SX322015《新松机器人快换应用操作手册》(A-0).md`, lines 370–373; corpus 5.0, revision V5.0 / A-0; object `c65fb49df9431e1e6a50fff13afe3b394cc49bf3d90c5bf70e56a7a6a3be0145`.

### Coding or diagnostic answer

根据《新松机器人快换应用操作手册》(V5.0/A-0)，快换作业通过 A02_TC 系列指令完成。基本流程为：(1) 用 Docking Unlock 放下当前工具；(2) 用 CheckOccupied 确认停靠站变为 Free（解锁成功）；(3) 用 Docking Lock 拾取并锁紧目标工具；(4) 用 CheckOccupied 确认停靠站变为 Occupied（锁紧成功）。工具编号范围 1–16，停靠站编号由实际配置决定。手册未单独给出停靠站、快换盘和 IO 的图形化配置步骤，仅提供了上述指令语法与参数说明。

### Example — tool_quick_change

机器人在焊接工位完成作业后，需将当前锁紧的焊接枪（ToolNo=1）从 1 号快换停靠站释放，确认解锁后拾取并锁紧抓取工具（ToolNo=2），最后确认锁紧到位。

**Environment and prerequisites:** 前提：A02_TC 快换模块已安装并通信正常；1 号停靠站已配置盖板与占用传感器；ToolNo=1（焊接枪）当前处于锁紧状态，ToolNo=2（抓取工具）已预置于停靠站。变量：StationNo=1（停靠站编号），当前工具 ToolNo=1，目标工具 ToolNo=2。

**Expected result:** 执行后，1 号停靠站先由 Occupied 变为 Free（工具 1 释放），再由 Free 变为 Occupied（工具 2 锁紧），完成一次快换。

**Manual:** SX322015《新松机器人快换应用操作手册》(A-0) V5.0 / A-0 [E1] [E3] [E5] [E8]

```text
A02_TC CheckTool ToolNo=1 检测当前连接工具为工具1
A02_TC Docking Unlock ToolNo=1 解锁当前工具1
A02_TC CheckOccupied StationNo=1 Free 确认解锁-检测支架无在位
A02_TC Docking Lock ToolNo=2 锁紧目标工具2
A02_TC CheckOccupied StationNo=1 Occupied 确认锁紧-检测支架工具在位
```

## [16/17] category_tracking

如何使用FL_GETV读取第一路传送带的实时速度，并在跟随作业中使用该速度？请说明R变量、通路参数及单位。

### Retrieved content summary

- 函数 **FL_GETV** 的说明部分指出：**参数1** 用于读取编码器的传送带实时速度，并将其赋值给用户实型变量 **R1**，单位为 **mm/s**。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322017《新松机器人跟随应用操作手册》(A-0)/SX322017《新松机器人跟随应用操作手册》(A-0).md`, lines 251–255; corpus 4.0, revision V5.0 / A-0; object `2cf2bc671983e4ff1a7dca64c3fc784d4336af86cbe22c11eb5358130a2e2b45`.

- 指令 `FL_GETV R10 F1` 用于获取第一路传送带的实时速度。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322017《新松机器人跟随应用操作手册》(A-0)/SX322017《新松机器人跟随应用操作手册》(A-0).md`, lines 530–533; corpus 4.0, revision V5.0 / A-0; object `199c3131d5014a25b3f983adbf361a9be9400427dee924c9abd0e5f5f3d3303a`.

- 指令 `FL_GETV R10 F1` 用于获取第一路传送带的实时速度。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322017《新松机器人跟随应用操作手册》(A-0)/SX322017《新松机器人跟随应用操作手册》(A-0).md`, lines 530–533; corpus 5.0, revision V5.0 / A-0; object `6c3185ef5be7b59e35deb760c4dbfc85ff2c9f6f3ec92e6a9b6eb00372c80501`.

- FL_GETV指令的说明：参数1用于读取编码器传送带的实时速度（单位mm/s）并赋值给用户实型寄存器R1。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322017《新松机器人跟随应用操作手册》(A-0)/SX322017《新松机器人跟随应用操作手册》(A-0).md`, lines 251–255; corpus 5.0, revision V5.0 / A-0; object `13c17ebee95c8ec7af59cab73e7bed971ca4baf03656ab6cd9fd7ea17300f91a`.

- 指令 `FL_GETV` 的功能是读取实时速度。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322017《新松机器人跟随应用操作手册》(A-0)/SX322017《新松机器人跟随应用操作手册》(A-0).md`, lines 242–246; corpus 4.0, revision V5.0 / A-0; object `61f482e91756e7d68b77a871341969bbc645266ea72248fb31dbd9f223c4e9be`.

- 该条目来自《新松机器人跟随应用操作手册》，说明函数 **FL_GETV** 的功能是 **读取实时速度**（该描述横跨两列，且所在单元格纵向合并覆盖后续5行）。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322017《新松机器人跟随应用操作手册》(A-0)/SX322017《新松机器人跟随应用操作手册》(A-0).md`, lines 242–246; corpus 5.0, revision V5.0 / A-0; object `b33735c4ded5b1ff51de28a4dd1f00281b7c8e6a4e5ac957a5212b9d463a7601`.

- FL_MOVL指令的参数1为编码器读取的传送带实时速度，单位mm/s。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322017《新松机器人跟随应用操作手册》(A-0)/SX322017《新松机器人跟随应用操作手册》(A-0).md`, lines 394–398; corpus 5.0, revision V5.0 / A-0; object `88a0b3649098c51c39b5096a50a6f38a561afa202e26ddf7552a8e8015a4c1d8`.

- FL_GETV 的格式为：FL_GETV R<参数1> F<参数2>。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322017《新松机器人跟随应用操作手册》(A-0)/SX322017《新松机器人跟随应用操作手册》(A-0).md`, lines 247–250; corpus 4.0, revision V5.0 / A-0; object `da348b5752d15743f54d92d17376ae78497214de0d86ae6c98882cb02157f143`.

### Coding or diagnostic answer

FL_GETV 用于读取编码器传送带的实时速度。格式为 FL_GETV R<参数1> F<参数2>，其中参数1为用户实型R变量（如R10），用于存储读取到的速度值，单位为mm/s；参数2为通路选择，F1对应第1路编码器，F2对应第2路编码器。读取后，该R变量可直接作为FL_MOVL指令的VL参数使用，使机器人沿用户X方向以传送带实时速度进行跟随运动。FL_MOVL格式为 FL_MOVL VL=R<速度> T=R<距离> #<参数文件号>，其中VL为速度（mm/s），T为行进直线距离（mm），#1~#8为偏移参数文件号。

### Example — tracking

机器人需要跟随第一路传送带上的工件进行连续作业。程序先设置速度百分比为100，然后通过FL_GETV读取第一路编码器对应的传送带实时速度并存入R10，最后使用FL_MOVL以该速度执行跟随直线运动，行进距离由R1指定，偏移量由参数文件#1定义。

**Environment and prerequisites:** 前提条件：传送带编码器已连接并正常工作；用户坐标系#1和工具坐标系#1已设定；速度百分比必须设为100。变量：R10为速度存储变量（mm/s），R1为行进距离变量（mm），#1为偏移参数文件号（可选1~8）。初始值：R10由FL_GETV实时写入，R1由用户根据工件行程设定。

**Expected result:** FL_GETV执行后，R10中存储第一路编码器对应的传送带实时速度（单位mm/s）。随后FL_MOVL以R10的速度驱动机器人沿用户X方向运动R1指定的距离，YZ方向偏移由#1参数文件决定，实现与传送带同步的跟随作业。

**Manual:** SX322017《新松机器人跟随应用操作手册》(A-0) V5.0 / A-0 [E1] [E2] [E7] [E8]

```text
SET VEL=100
FL_GETV R10 F1
FL_MOVL VL=R10 T=R1 #1
```

## [17/17] category_vision

如何给相机发送拍照指令、获取测量结果并计算位姿偏移？请按同一手册版本说明视觉作业参数及指令调用顺序。

### Retrieved content summary

- 该表格定义了一个用于**获取相机测量结果**的功能接口，其调用格式为 `VSGPI PO#=（参数1） NO=（参数2）`。

具体参数配置如下：
*   **参数1**：对应 **视觉场景组**
*   **参数2**：对应 **视觉作业号**
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322005《新松机器人视觉应用操作手册》（A-1)/SX322005《新松机器人视觉应用操作手册》（A-1).md`, lines 426–443; corpus 4.0, revision V5.0 / A-1; object `67e7e8a38aa7ca8e2d355f9193ba99ae0dc2af2b885d53d581073c0e56c91b65`.

- 功能：给相机发送拍照指令。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322005《新松机器人视觉应用操作手册》（A-1)/SX322005《新松机器人视觉应用操作手册》（A-1).md`, lines 409–412; corpus 4.0, revision V5.0 / A-1; object `54a400cb18dd449c22f1ca9aad4d21df8006ffbf28f4646a7c7f25cf439e68be`.

- 该表格定义了功能指令 `VSGPI_N_P`，用于**获取相机测量结果**。

该指令包含四个参数（N, T, W, A），具体定义如下：
*   **参数1 (N)**：动作标志（0：视觉准备；1：触发测量）
*   **参数2 (T)**：功能模式（0：定位；1：打磨质量检测；2：凸起高度计算）
*   **参数3 (W)**：工件号（0-65535）
*   **参数4 (A)**：区域号（0-65535）；若在凸起高度计算模式下，兼作左右区分标志（0：左；1：右）
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322005《新松机器人视觉应用操作手册》（A-1)/SX322005《新松机器人视觉应用操作手册》（A-1).md`, lines 476–501; corpus 4.0, revision V5.0 / A-1; object `6235ecdd1ea97cbc2c9c60af869250f1009cf308a823fe9c12423de07734d845`.

- 功能：给相机发送拍照指令
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322005《新松机器人视觉应用操作手册》（A-1)/SX322005《新松机器人视觉应用操作手册》（A-1).md`, lines 451–454; corpus 4.0, revision V5.0 / A-1; object `da743cf2e7347e3af430fae472c4c7fcef43e6e31bae76fd3d63ca524a0e0340`.

- 该表格定义了用于**获取相机测量结果**的视觉系统指令格式 **`VSGPI PO#=（参数1） NO=（参数2）`**，并说明了两个关键参数的含义：**参数1** 指定**视觉场景组**，**参数2** 指定**视觉作业号**。
  Source: `/d/devel/rag/ribosome/assets/code-docs.5.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322005《新松机器人视觉应用操作手册》（A-1)/SX322005《新松机器人视觉应用操作手册》（A-1).md`, lines 426–443; corpus 5.0, revision V5.0 / A-1; object `cc120c4b8dea57918cc2045d25bc580c6d36493d3406281d96945072c4815808`.

- 功能：获取相机测量结果
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322005《新松机器人视觉应用操作手册》（A-1)/SX322005《新松机器人视觉应用操作手册》（A-1).md`, lines 480–483; corpus 4.0, revision V5.0 / A-1; object `5daf662f6b3aee7132e8e76afba8afdad7f91957f8e79f87cc6e43f04d11ed4d`.

- 功能：获取相机测量结果
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322005《新松机器人视觉应用操作手册》（A-1)/SX322005《新松机器人视觉应用操作手册》（A-1).md`, lines 430–433; corpus 4.0, revision V5.0 / A-1; object `80d1559762a13c0bf454438236ab4b82e849b51e203f5d1c387db60f2c337cec`.

- 该表定义了命令 `VSTG_N_P` 的参数结构及功能，用于**给相机发送拍照指令**。

*   **功能**：触发相机拍照。
*   **参数说明**：
    *   **参数1 (N)**：动作标志，0代表视觉准备测量，1代表触发视觉测量（范围：0-255）。
    *   **参数2 (T)**：功能模式选择，0代表定位，1代表打磨质量检测，2代表凸起高度计算（范围：0-255）。
    *   **参数3 (W)**：工件号（范围：0-65535）。
    *   **参数4 (A)**：区域号（范围：0-65535）；当参数2为2（凸起高度计算）时，该参数作为左右区分标志，0代表左，1代表右。
  Source: `/d/devel/rag/ribosome/assets/code-docs.4.0/.md/06 产品手册/软件类/手册/V5.0版本/SX322005《新松机器人视觉应用操作手册》（A-1)/SX322005《新松机器人视觉应用操作手册》（A-1).md`, lines 447–472; corpus 4.0, revision V5.0 / A-1; object `2d98089353bcf99359709b0a39395aa638658e54e6a466ff0e79fbc5cfeeba9f`.

### Coding or diagnostic answer

根据《新松机器人视觉应用操作手册》（A-1）V5.0版本，视觉作业中给相机发送拍照指令并获取测量结果的调用顺序为：首先使用 VSTG_N_P 指令以 N=0（视觉准备测量）进行初始化，然后以 N=1（触发视觉测量）正式触发拍照，最后使用 VSGPI_N_P 指令获取相机测量结果用于计算位姿偏移。VSTG_N_P 的参数包括：N（动作标志，0=准备/1=触发）、T（功能类型，0=定位/1=打磨质量检测/2=凸起高度计算）、W（工件号，0-65535）、A（区域号，0-65535，凸起高度计算时0=左/1=右）。VSGPI_N_P 参数结构相同，用于读取对应测量结果。

### Example — vision

机器人在装配工位上需要利用视觉系统对工件进行定位测量：先准备视觉测量环境，再触发相机拍照，最后读取测量结果以计算工件位姿偏移量并修正机器人末端轨迹。

**Environment and prerequisites:** 视觉场景已配置完成；视觉场景组编号为 1（占位符）；视觉作业号为 1（占位符）；功能类型 T=0 表示调用定位功能；工件号 W=1；区域号 A=0；动作标志 N=0 为视觉准备测量，N=1 为触发视觉测量。

**Expected result:** 第一条指令完成视觉测量准备；第二条指令触发相机拍照并执行定位测量；第三条指令返回测量结果（含位姿偏移数据），供后续运动补偿使用。

**Manual:** SX322005《新松机器人视觉应用操作手册》（A-1） V5.0 / A-1 [E4] [E8] [E3] [E6]

```text
VSTG_N_P N=0 T=0 W=1 A=0
VSTG_N_P N=1 T=0 W=1 A=0
VSGPI_N_P N=1 T=0 W=1 A=0
```

,case_id,category,hits,context_chars,omissions,missing_manuals,example_status,error
0,category_adhesive_dispensing,adhesive_dispensing,8,12971,0,0,included,
1,category_arc_welding,arc_welding,8,17215,0,0,included,
2,category_fds,fds,8,6403,0,0,included,
3,category_grinding,grinding,8,10491,0,0,unsupported,
4,category_laser_welding,laser_welding,8,11921,0,0,included,
5,category_load_analysis,load_analysis,8,4460,0,0,unsupported,
6,category_material_handling,material_handling,8,9870,0,0,included,
7,category_offline_interface,offline_interface,8,18685,0,0,unsupported,
8,category_palletizing,palletizing,8,8970,0,0,unsupported,
9,category_pneumatic_spot_welding,pneumatic_spot_welding,8,9161,0,0,included,
10,category_spot_welding,spot_welding,8,7826,0,0,included,
11,category_spr_riveting,spr_riveting,8,10825,0,0,included,
12,category_stud_welding,stud_welding,8,10354,0,0,included,
13,category_teaching_free_welding,teaching_free_welding,8,10372,0,0,unsupported,
14,category_tool_quick_change,tool_quick_change,8,8147,0,0,included,
15,category_tracking,tracking,8,7859,0,0,included,
16,category_vision,vision,8,6530,0,0,included,

## Cleanup
Run after the selected category tests, or after interruption.

In [ ]:
# | notest
try:
    if 'app' in globals(): app.close()
finally:
    for client_name in ('embedding_client', 'generation_client'):
        if client_name in globals(): await globals()[client_name]._client.aclose()